### ISSUE TITLE
[Private-Synthetics] Conditionally create config map 

### ISSUE THREAD

**Issue by johnkost** [DataDog/helm-charts#103]
While installing the private synthetics chart, I noticed that I was forced to create a config map with the configuration. Since this contains secret information, I want to create this out of band (or using another tool that handles secrets). It would be nice if the chart allowed me to conditionally create the configMap (or potentially used a secrets so I could use external secrets for this).

**Comment by loutPhilipps** [comment]
👋🏼 This should have been covered by https://github.com/DataDog/helm-charts/pull/682, feel free to re-open this issue if it doesn't do what you want!
