### ISSUE TITLE
api service metrics are only collected when the feature flag is set to `false`

### ISSUE THREAD

**Issue by L7R7** [DataDog/helm-charts#1063]
**Describe what happened:**

I think this is a followup to #1057. We set `datadog.kubeStateMetricsCore.collectApiServicesMetrics` to `true` because we need `kubernetes_state.*` metrics, but with version 3.30.7, metrics only show up when the flag is set to `false`

**Describe what you expected:**

From what I read in the code of the PR and the docs for the flag, I was expecting the opposite behavior, where metrics appear only if the flag is set to `true`

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS: v1.26.4-eks-0a21954

**Comment by L7R7** [comment]
@tbavelier I think I got it, thank you for the explanation

Just to make sure:

> If you set the flag to false, you get the previous/normal behaviour, collection of kubernetes_state.* metrics

will this change in a future version? we rely on `kubernetes_state.deployment.replicas_desired`, will we have to change the flag to `true` at some point in order to still get this metric?

**Comment by tbavelier** [comment]
@L7R7 We might switch the flag to `true` in a future version, but that would only add more metrics, it won't change the collection of already/previously collected metrics such as the one you shared, so you won't need to take any actions in the foreseeable future to keep collecting `kubernetes_state.deployment.replicas_desired`.

**Comment by L7R7** [comment]
@tbavelier that's great, thank you for clarifying! I'm closing this issue
