### ISSUE TITLE
Restrict ClusterRole policy for MutatingWebhookConfigurations to the Datadog mutating webhook

### ISSUE THREAD

**Issue by nilushancosta** [DataDog/helm-charts#1071]
**Describe what happened:**
`<release-name>-cluster-agent` ClusterRole has the following PolicyRule.
```
PolicyRule:
  Resources                                                   Non-Resource URLs  Resource Names       Verbs
  ---------                                                   -----------------  --------------       -----
  mutatingwebhookconfigurations.admissionregistration.k8s.io  []                 []                   [get list watch update create]
```
Ref - https://github.com/DataDog/helm-charts/blob/b6f7f7b855c661d8af4af67091cb846ebb1c8e55/charts/datadog/templates/cluster-agent-rbac.yaml#L224

This policy provides permission to perform all these actions on any mutating webhook in the cluster. 

**Describe what you expected:**
Is it possible to modify the above policy as follows and restrict it to the Datadog mutating webhook only?
(Datadog mutating webhook is named `datadog-webhook`)
```
PolicyRule:
  Resources                                                   Non-Resource URLs  Resource Names       Verbs
  ---------                                                   -----------------  --------------       -----
  mutatingwebhookconfigurations.admissionregistration.k8s.io  []                 [datadog-webhook]    [get list watch update create]
```

**Steps to reproduce the issue:**
1. Install Datadog from the Helm chart
2. Check the policy rules of the `<release-name>-cluster-agent` ClusterRole

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by nilushancosta** [comment]
Please find some additional details below.
Helm chart version: 3.30.10
agent docker image: datadoghq/agent:7.43.1
cluster-agent docker image: datadoghq/cluster-agent:7.43.1

With the current policy, it can even `update` and `create` any mutating webhook in the entire cluster. From a security point of view, since this cluster role is only used by Datadog, it would be better to restrict `mutatingwebhookconfigurations.admissionregistration.k8s.io` to specific resources. It would help to reduce the attack surface in the Kubernetes cluster.

**Comment by celenechang** [comment]
Hi @nilushancosta thank you for reporting. This was addressed in https://github.com/DataDog/helm-charts/pull/1110 and https://github.com/DataDog/helm-charts/pull/1148 .
