### ISSUE TITLE
Set DATADOG_HOST automatically

### ISSUE THREAD

**Issue by PSanetra** [DataDog/helm-charts#113]
When setting up the Cluster Agent external metric server it is necessary to define `DATADOG_HOST` if you are using an EU account.

I think this environment variable should default to `https://api.{{ .Values.datadog.site }}`.

See https://docs.datadoghq.com/agent/cluster_agent/external_metrics/#custom-metrics-server and https://github.com/zorkian/go-datadog-api/blob/9e2c892691035a7685a16d5839910cfc54e42fb6/client.go#L55

Related: https://github.com/helm/charts/issues/22723

**Comment by vboulineau** [comment]
Hey @PSanetra,

This issue is more linked to the Cluster Agent itself. Hopefully it will be fixed by this PR:
https://github.com/DataDog/datadog-agent/pull/7214

Available when we release Cluster Agent 1.11

**Comment by PSanetra** [comment]
@vboulineau so in the future it should be enough, to set `datadog.site` on the Helm release, right?

**Comment by vboulineau** [comment]
Yes correct

**Comment by clamoriniere** [comment]
Hi @PSanetra 

The `datadog` chart version `2.9.9` should solve your issue. From this version the default agent and cluster-agent image tags have been updated. 
The new cluster-agent `1.11.0` should have the fix mention by @vboulineau.

Please let us know if it solve your issue.

Thanks
Cedric
