### ISSUE TITLE
Service "staging-datadog-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by rchenzheng** [DataDog/helm-charts#117]
**Describe what happened:**
Upgrading the chart causes a change on the cluster ip

```
Error: UPGRADE FAILED: failed to replace object: Service "staging-datadog-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Describe what you expected:**
The release should've just upgraded successfully

**Steps to reproduce the issue:**
Deploy then upgrade the chart

**Additional environment details (Operating System, Cloud provider, etc):**
HELM 3.4.1

version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Chart version 2.4.2

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by billieblaze** [comment]
having a similar problem.    i'm fine assigning the KSM service a static-ish IP, but I don't see an immediate way to set that up.

**Comment by ahmed-mez** [comment]
Hi all, thank you for opening this issue.

It seems like it's a known kube-state-metrics helm chart issue and is impacting the charts importing it. I think as a workaround you can delete the service manually (`k delete svc -n <your datadog namespace> staging-datadog-kube-state-metrics` in your case)

Let us know if this works.

Thanks!
