### ISSUE TITLE
Chart conflicts with existing v1beta1.external.metrics.k8s.io resource

### ISSUE THREAD

**Issue by GuillaumeLachaud** [DataDog/helm-charts#118]
**Describe what happened:**
```
helm install  datadog-monitoring \                                                                                                                                                                   
    --set datadog.apiKey=MY_KEY \
    --set datadog.appKey=MY_KEY\
    --set clusterAgent.enabled=true \
    --set clusterAgent.metricsProvider.enabled=true \
    datadog/datadog
```
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "v1beta1.external.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "datadog-monitoring"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "datadog"`

**Describe what you expected:**
Chart would have been installed properly

**Steps to reproduce the issue:**
Run the commands from the README on a cluster that already have some external metrics such as https://github.com/awslabs/k8s-cloudwatch-adapter

**Additional environment details (Operating System, Cloud provider, etc):**
EKS, with K8s 1.17

**Comment by ahmed-mez** [comment]
Hey @GuillaumeLachaud, this is actually a limitation in Kubernetes itself as it doesn't allow multiple external metric providers (see https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/70). Thanks!
