### ISSUE TITLE
parse error at (datadog/templates/_helpers.tpl:855): unclosed action

### ISSUE THREAD

**Issue by rderbyshire-asura** [DataDog/helm-charts#1217]
We've hit the following error whilst running our build using Helm3 on CircleCI:

```
"datadog" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "datadog" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: UPGRADE FAILED: parse error at (datadog/templates/_helpers.tpl:855): unclosed action
```

Our last successful run was back on September 19th. Took a look at the data/templates/_helpers.tpl and can see it's been updated since then, but with nothing that suggests an unclosed action.

**Comment by celenechang** [comment]
Hi @rderbyshire-asura , I am not able to reproduce the issue; are you still experiencing this? Do you mind providing some more details such as the chart version you were/are on and the command that produced the error?

**Comment by keg** [comment]
Hi, I've hit the same error. Looks present in chart versions >= 3.42.0. I'm on helm version v3.6.1.

**Comment by argee5285** [comment]
I am getting the same error
`"stderr": "Error: UPGRADE FAILED: parse error at (datadog/templates/_helpers.tpl:855): unclosed action", "stderr_lines": ["Error: UPGRADE FAILED: parse error at (datadog/templates/_helpers.tpl:855): unclosed action"]`

~:/tmp/tmp.Bu0W2oTWlj$ helm show chart datadog/datadog
`apiVersion: v1
appVersion: "7"
dependencies:
- condition: clusterAgent.metricsProvider.useDatadogMetrics
  name: datadog-crds
  repository: https://helm.datadoghq.com
  tags:
  - install-crds
  version: 1.0.1
- condition: datadog.kubeStateMetricsEnabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 2.13.2
description: Datadog Agent
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
keywords:
- monitoring
- alerting
- metric
maintainers:
- email: support@datadoghq.com
  name: Datadog
name: datadog
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
version: 3.43.1`

~:/tmp/tmp.Bu0W2oTWlj$ helm version
`version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}`

**Comment by celenechang** [comment]
Thank you for the details; I wonder if you are facing an issue similar to that described [here](https://github.com/arttor/helmify/issues/11). As I can't reproduce the issue, would you be able to verify that consolidating [these lines](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_helpers.tpl#L855-L856) into a single line resolves the error for you?

**Comment by celenechang** [comment]
Update: I was able to figure out a way to reproduce the issue with an older Helm chart version. Indeed consolidating the lines seems to fix it; I will make a quick chart update to unblock you.
