### ISSUE TITLE
Not able to run custom metric check on a single agent on k8s

### ISSUE THREAD

**Issue by mukul-c2fo** [DataDog/helm-charts#125]
**Describe what happened:**

We are installing datadog through this helm chart on our Kubernetes clusters. Recently we got a requirement of adding a custom metric for which we added a python script in checksd section of values.yaml and corresponding confd for scheduling that check. 

Everything works fine and we are able to export the custom metric but the check runs on all the agents which are running on the cluster.

**Describe what you expected:**

We expected the check to run once on a single cluster. 

Is there a way to configure below section of confd for a custom check through this chart?

**instances: [{}]**

**Steps to reproduce the issue:**

We followed the official documentation to create the check and the override values.yaml looks like below:

https://docs.datadoghq.com/developers/write_agent_check/?tab=agentv6v7

**Values.yaml**

```
datadog:
    checksd:
      my_custom_check.py: |-

    confd:
      my_custom_check.yaml: |-
        init_config:
        instances: [{}]
```

**Additional environment details (Operating System, Cloud provider, etc):

OS: Linux

Cloud Provider: AWS.

**Comment by vboulineau** [comment]
Hello @mukul-c2fo,

What you're looking for is a Cluster Check: https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/

Basically you will still mount your custom check in `checksd` of all Agents, but you will mount the check config in the Cluster Agent that will dispatch a single instance on a (random without advanced dispatching) Agent.

**Comment by mukul-c2fo** [comment]
Thanks @vboulineau - Will try this out. 

Also, can I configure tags in `instances: [{}] ` instead of passing those in the gauge method of my python script?

**Comment by mukul-c2fo** [comment]
> Hello @mukul-c2fo,
> 
> What you're looking for is a Cluster Check: https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/
> 
> Basically you will still mount your custom check in `checksd` of all Agents, but you will mount the check config in the Cluster Agent that will dispatch a single instance to an Agent. (random without advanced dispatching)

I started getting below error while tying this mechanism. 

```
  Loading Errors
  ==============
    my_custom_check
    --------------------------
      Core Check Loader:
        Check my_custom_check not found in Catalog
        
      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so
        
      Python Check Loader:
        unable to import module 'my_custom_check': No module named 'my_custom_check'
```

**Comment by ahmed-mez** [comment]
Hi @mukul-c2fo you basically need to keep this `checksd` config 

```
datadog:
    checksd:
      my_custom_check.py: |-
```

and add the `confd ` config under `clusterAgent.confd` with `cluster_check: true` in the check config

```
clusterAgent:
  confd:
    my_custom_check.yaml: |-
      cluster_check: true
      init_config:
      instances: [{}]
```

**Comment by mukul-c2fo** [comment]
Thanks Ahmed for your time, we got it working.

**Comment by ahmed-mez** [comment]
Glad to hear that, thank you @mukul-c2fo !
