### ISSUE TITLE
AutoPilot deployments fail on 3.47+ if using a EU site value

### ISSUE THREAD

**Issue by Baune8D** [DataDog/helm-charts#1257]
**Describe what happened:**
Chart versions starting from `3.47.0` now breaks AutoPilot deployments if using an EU site value.

**Describe what you expected:**
I expected it to deploy without issues.

**Steps to reproduce the issue:**
Deploy the helm chart with value `site: datadoghq.eu`

**Additional environment details (Operating System, Cloud provider, etc):**
GKE AutoPilot

**Comment by fanny-jiang** [comment]
Hi @Baune8D, thanks for reaching out about this and I apologize for the inconvenience. We're aware of the issue and are actively working with GKE Autopilot to push an updated allowlist for the EU (and asia) GCR registries. I'll follow up on this thread when the updated allowlist is available. We appreciate your patience.
