### ISSUE TITLE
Pods with non-default serviceaccount fail to reach Datadog Admission Controller

### ISSUE THREAD

**Issue by NHMPB** [DataDog/helm-charts#1267]
**Describe what happened:**
We currently have a setup with working public AWS EKS cluster, our services deployed and running and Datadog installed via Helm chart including Admission Controller. Everything is working fine. Now we wanted to add individual Service Accounts to our pods, but as soon as we modify the deployment to use the new service accounts, they are not starting anymore.

The new replicaset has this error:
```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  16m (x20 over 62m)  replicaset-controller  Error creating: Timeout: request did not complete within requested timeout - context deadline exceeded
```

In the K8s API Server logs I can see these errors:
```
W1207 16:13:16.847842      10 dispatcher.go:189] Failed calling webhook, failing open datadog.webhook.auto.instrumentation: failed calling webhook "datadog.webhook.auto.instrumentation": failed to call webhook: Post "https://datadog-agent-cluster-agent-admission-controller.datadog.svc:443/injectlib?timeout=10s": context deadline exceeded

E1207 16:13:16.847865      10 dispatcher.go:193] failed calling webhook "datadog.webhook.auto.instrumentation": failed to call webhook: Post "https://datadog-agent-cluster-agent-admission-controller.datadog.svc:443/injectlib?timeout=10s": context deadline exceeded

W1207 16:13:20.842168      10 dispatcher.go:189] Failed calling webhook, failing open datadog.webhook.config: failed calling webhook "datadog.webhook.config": failed to call webhook: Post "https://datadog-agent-cluster-agent-admission-controller.datadog.svc:443/injectconfig?timeout=4s": context deadline exceeded

E1207 16:13:20.842218      10 dispatcher.go:193] failed calling webhook "datadog.webhook.config": failed to call webhook: Post "https://datadog-agent-cluster-agent-admission-controller.datadog.svc:443/injectconfig?timeout=4s": context deadline exceeded
```

Adding more permissions to the role does not seem to help. I even tried wildcards everywhere, just to confirm it's not a permission issue:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: product-env
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-07T12:37:59Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: product-role
  namespace: preprod
  resourceVersion: "177615476"
  uid: d93ef600-d2ac-4daa-a008-7acc26ff927d
rules:
- apiGroups:
  - '*'
  resourceNames:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

As soon as we remove serviceaccount from our pods again, they are just starting fine again and data is available in Datadog. Also, removing the `admission.datadoghq.com/enabled: "true"` label from our pods works, even with our custom serviceaccount. So from my perspective, it's unlikely to be a network issue.

**Describe what you expected:**
Our pods should be able to connect to the Admission Controller and be able to start.

**Steps to reproduce the issue:**
1. Have a Kubernetes cluster with Datadog helm chart installed and Admission Controller enabled
2. Create custom `serviceaccount`, `role` and `rolebinding`
3. Assign custom serviceaccount to pod template in deployment
4. Deploy

**Additional environment details (Operating System, Cloud provider, etc):**
Not sure if this is related, but the serviceaccounts are using Pod Identity feature to get AWS IAM roles assigned.
Helm chart version is 3.11.0

**Comment by JuHarm89** [comment]
We have the exact same issue. We are also using a custom serviceAccount on the pod template that uses the AWS IAM feature. Have you found some workaround that does not require to remove the custom serviceAccount from the Pods?

**Comment by NHMPB** [comment]
No, not yet unfortunately. I disabled admission controller for those pods for now to be able to use service accounts. Datadog is configured manually so Admission Controller is not necessarily needed until fixed.

**Comment by NHMPB** [comment]
Your are right, I checked that config on our side also again and due to a typo there was an error in the Firewall rule. Now this is working also for us.
