### ISSUE TITLE
Helm chart doesn't install the agent anymore?

### ISSUE THREAD

**Issue by jeremyd** [DataDog/helm-charts#134]
I've been using datadog to monitor my kubernetes cluster.  When I uninstalled a working agent, deleted the namespace and performed a re-install and now it only installs kube-state-metrics and NOT the daemon set.  I can't figure out why it's not installing the daemonset as my config is un-changed.  I also tried using the default-values from the source repo still no luck.  I don't get any errors or anything it just doesn't even try to install the daemonset.  The only pod that runs is kube-state-metrics.

**Steps to reproduce the issue:**
datadog-values.yaml
```
datadog:
  agents:
    enabled: true
  apm:
    enabled: true
  logs:
    enabled: false
```

```
$ helm install datadog-agent datadog/datadog -f datadog_new_values.yaml --dependency-update --set targetSystem=linux --set datadog.apiKey=$DD_API_KEY

NAME: datadog-agent
LAST DEPLOYED: Thu Jan  7 12:40:11 2021
NAMESPACE: datadog
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Datadog agents are spinning up on each node in your cluster. After a few
minutes, you should see your agents starting in your event stream:
    https://app.datadoghq.com/event/stream

The Datadog Agent is listening on port 8126 for APM service.

$ kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
datadog-agent-kube-state-metrics-784796cf46-xvsms   1/1     Running   0          2m25s
```

```


**Additional environment details (Operating System, Cloud provider, etc):**
```
helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4300", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-10-28T09:23:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by ahmed-mez** [comment]
Hey @jeremyd thanks for opening the issue and sorry for the trouble! 

Could you please make sure you use the latest chart version?

```
helm repo add datadog https://helm.datadoghq.com
helm repo update
```

Just to confirm, you shared in the description the content of `datadog-values.yaml` but in the helm install command you pass `datadog_new_values.yaml` as argument, could you share the content of `datadog_new_values.yaml` ?

It could also be interesting to run `helm template datadog-agent datadog/datadog -f <your values file>` and see whether the Daemonset manifest is present.

If these steps couldn't help you identify and fix the issue, please don't hesitate to [contact or solutions team](https://www.datadoghq.com/support/).

Thanks!

**Comment by jeremyd** [comment]
Hi @ahmed-mez 

Yes I'm using the latest helm chart v2.6.7 from the helm.datadoghq.com repo.

The values are the same, I'm using datadog-values.yaml after confirming that using the stock values.yaml with the modifications from the stripped down version has the same result.

When I run 'helm template datadog-agent datadog/datadog -f <your values file>' it shows a DaemonSet.  However, when I run helm install --debug, it does not show a DaemonSet.  When I run helm upgrade or install it shows 10 resources:

```
history.go:53: [debug] getting history for release datadog-agent
upgrade.go:121: [debug] preparing upgrade for datadog-agent
upgrade.go:129: [debug] performing update for datadog-agent
upgrade.go:301: [debug] creating upgraded release for datadog-agent
client.go:187: [debug] checking 10 resources for changes
client.go:450: [debug] Looks like there are no changes for ServiceAccount "datadog-agent"
client.go:450: [debug] Looks like there are no changes for Secret "datadog-agent"
client.go:450: [debug] Looks like there are no changes for ConfigMap "datadog-agent-installinfo"
client.go:450: [debug] Looks like there are no changes for ClusterRole "datadog-agent-kube-state-metrics"
client.go:450: [debug] Looks like there are no changes for ClusterRole "datadog-agent"
client.go:450: [debug] Looks like there are no changes for ClusterRoleBinding "datadog-agent-kube-state-metrics"
client.go:450: [debug] Looks like there are no changes for ClusterRoleBinding "datadog-agent"
client.go:450: [debug] Looks like there are no changes for Service "datadog-agent-kube-state-metrics"
upgrade.go:136: [debug] updating status for upgraded release for datadog-agent
Release "datadog-agent" has been upgraded. Happy Helming!
```

**Comment by jeremyd** [comment]
Ok, I just tested with an older helm version and it works.  So this must be a bug in either helm or the chart with newer helm.

```
helm version (silently does not create daemonset)
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

```
helm version (works)
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Comment by ahmed-mez** [comment]
Thanks @jeremyd for the additional information

> is there a dependency cache somewhere or anything from a previous helm install of this chart?

The only dependencies we have are `datadog-crds` and `kube-state-metrics` as mentioned [here](https://github.com/DataDog/helm-charts/blob/datadog-2.6.7/charts/datadog/requirements.yaml), I don't see how this could affect the DaemonSet installation though.

**Comment by jeremyd** [comment]
I wiped all my configs and uninstalled all my plugins (like the secrets plugin).  Then I re-added the repos and it works again.  Not sure why, thanks for the help.
