### ISSUE TITLE
The release 3.58.0 is not yet available

### ISSUE THREAD

**Issue by shfranc** [DataDog/helm-charts#1344]
**Describe what happened:**
The release `3.58.0` is not yet available in the `https://helm.datadoghq.com/` repository but it's listed [as the latest release](https://github.com/DataDog/helm-charts/releases/tag/datadog-3.58.0) on this Github repository.

**Describe what you expected:**
I expect to be able to install the helm chart 3.58.0 for the datadog agent or to understand why it's not yet published on the helm chart repository.
If there is a delay or something I'm not aware of, let me know !
Thanks 👍🏼 

**Steps to reproduce the issue:**
```
helm repo add datadog https://helm.datadoghq.com
"datadog" has been added to your repositories

helm search repo datadog/datadog
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION
datadog/datadog         	3.57.3       	7          	Datadog Agent
datadog/datadog-crds    	1.4.0        	1          	Datadog Kubernetes CRDs chart
datadog/datadog-operator	1.5.1        	1.4.0      	Datadog Operator
```

**Comment by celenechang** [comment]
Hi @shfranc and all, many apologies for this issue. It has been resolved.
