### ISSUE TITLE
Make the datadog CRD 1.5.x available with the Operator

### ISSUE THREAD

**Issue by renuka-sharma** [DataDog/helm-charts#1350]
**Describe what happened:**
 Would be nice to have the operator version 1.5.x crds available with the Datadog Operator

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by renuka-sharma** [comment]
I am aiming to setup SingleStepInstrumentation for our Setup which is not yet available in the Older CRD definition : https://github.com/DataDog/datadog-operator/blob/main/config/crd/bases/v1/datadoghq.com_datadogagents.yaml#L7842

**Comment by celenechang** [comment]
Hi @renuka-sharma , after Datadog Operator 1.5.0 has been released we will update the CRDs in the chart. Thank you
