### ISSUE TITLE
A container name must be specified for pod

### ISSUE THREAD

**Issue by jsaguiar** [DataDog/helm-charts#139]
**Describe what happened:**
Follow the documentation` https://docs.datadoghq.com/agent/kubernetes/?tab=helm` just changed 
```
 logs: 
    enabled: true
    containerCollectAll: true
```

I expected to have some logs to be forward to datadob, but nothing happens.

Looking at logs I get;
```
$kubectl logs datadog-9z7z6                              
error: a container name must be specified for pod datadog-9z7z6, choose one of: [agent process-agent] or one of the init containers: [init-volume init-config]
```

**Describe what you expected:**
Logs to be forward

**Steps to reproduce the issue:**
`$helm upgrade --install datadog -f datadog-new.yaml --set datadog.site='datadoghq.com' --set datadog.apiKey=*** --set targetSystem=linux datadog/datadog`

**Additional environment details (Operating System, Cloud provider, etc):**
Azure aks

**Comment by celenechang** [comment]
Hi @jsaguiar ! To view logs with `kubectl`, you can try specifying a container with `kubectl logs <pod-name> -c <container-name>`. For instance, for the agent container of your pod:

```kubectl logs datadog-9z7z6 -c agent```

Regarding the absence of log collection in Datadog, please [reach out to our support team](https://docs.datadoghq.com/help/) and we would be happy to help!
