### ISSUE TITLE
index.yaml generated field not being updated

### ISSUE THREAD

**Issue by Niksko** [DataDog/helm-charts#142]
**Describe what happened:**

The `generated` field of this Helm repository's `index.yaml` is not being updated. Flux v2 expects this field to change. When it stays the same, Flux assumes there are no changes to the index and so doesn't pull a new index file with new releases.

**Describe what you expected:**

The `generated` field of the index should match the latest timestamp that the Helm repository was updated.

**Steps to reproduce the issue:**

```
$ curl -s https://helm.datadoghq.com/index.yaml | grep generated
generated: "2020-07-29T11:03:41.153796856Z"
```

**Additional environment details (Operating System, Cloud provider, etc):**

This is a bug in helm/chart-releaser. I've added a fix in this PR: https://github.com/helm/chart-releaser/pull/99. Once that is merged, we will need to update to the latest release of the chart releaser Github action when it is released

**Comment by vboulineau** [comment]
Thanks, we'll follow up and update when available
