### ISSUE TITLE
Use new kube-state-metrics Helm chart

### ISSUE THREAD

**Issue by walkafwalka** [DataDog/helm-charts#151]
The Datadog chart depends on the [deprecated kube-state-metrics Helm chart](https://github.com/helm/charts/tree/master/stable/kube-state-metrics). In #89, pointing to https://charts.helm.sh/stable prevents the deployment failure but did not update the chart to the [new kube-state-metrics Helm chart](https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics).

Relates to #75.

**Comment by clamoriniere** [comment]
Thanks for opening this issue.

It looks like that the new chart contains some breaking change compare the previous chart repo. 
So we need to investigate how we can accommodate theses change without breaking our configuration.

**Comment by L3n41c** [comment]
Hello @walkafwalka,
The KSM dependency has been upgraded in #194.
