### ISSUE TITLE
rbac deprecation notice when installing helm chart

### ISSUE THREAD

**Issue by krknopp** [DataDog/helm-charts#153]
**Describe what happened:**
When I install the helm chart for the Datadog agent, I get a warning about the deprecation of the RBAC beta api.  

```
W0126 17:35:02.320670   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0126 17:35:02.358430   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0126 17:35:02.396070   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0126 17:35:02.660601   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0126 17:35:02.698056   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0126 17:35:02.736238   42468 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```

I had previously installed the Datadog agents via the daemonset.  I think I got it all removed before trying to install the agents via `helm`.  It installs fine other than the warning.

When I look at the [source](https://github.com/DataDog/helm-charts/blob/5d1c43d9ee9a827b619b9ee183cce3f2908171a2/charts/datadog/templates/_helpers.tpl), it looks like `Capabilities.KubeVersion.GitVersion` is used to determine the API version and this [issue](https://github.com/helm/charts/issues/20918) that field is deprecated and I'm wondering if our cluster is new enough to not have that field.

**Describe what you expected:**
No warnings when I install/upgrade the helm chart

**Steps to reproduce the issue:**
helm install datadog-agent -f values.yaml --set datadog.apiKey=<API KEY> datadog/datadog

**Additional environment details (Operating System, Cloud provider, etc):**
Azure AKS 1.19.3 (Linux)

**Comment by krknopp** [comment]
I have had this problem with versions 2.8.3 and 2.8.4 and the 2.7.2 of the helm chart on AKS clusters secured with Service Principals and Managed Identities running both kubenet and CNI for networking.  I have the same problem on AKS 1.19.6.

**Comment by ahmed-mez** [comment]
Hi @krknopp 

Thank you for opening this issue, this is tracked on our side and we'll make sure to update the chart to use the new APIs for new cluster versions before the release of Kubernetes v1.22+

Thanks!
