### ISSUE TITLE
Can we set this DD_APPSEC_ENABLED to false for non-PHP applications?

### ISSUE THREAD

**Issue by smartaquarius10** [DataDog/helm-charts#1544]
Hello,

Can we set `DD_APPSEC_ENABLED `to `false `to disable threat management for non-PHP applications as well?

I was reading [this article](https://docs.datadoghq.com/security/application_security/troubleshooting/#disabling-threat-management-and-protection), which mentions removing this variable for non-PHP apps and explicitly setting it to false for PHP apps.

In CI/CD environments, it can be challenging to handle such scenarios and identify the type of application a user is working with. If we set it to false for all types of applications, will this disable threat management in the same way as completely removing this variable?

**Comment by aquiladayc** [comment]
Hello @smartaquarius10 , I guess it better suits for https://github.com/DataDog/datadog-agent, can you redirect it?
