### ISSUE TITLE
Error installing helm chart 3.81.1 on GKE Autopilot

### ISSUE THREAD

**Issue by ccamachofg** [DataDog/helm-charts#1621]
Hello,

I'm trying to deploy datadog on a GKE Autopilot cluster with the following values

```yaml
datadog:
  apiKey: "1111111111111"
  logs:
    enabled: true
providers:
  gke:
    autopilot: true
```
And, I keep getting the error:

> Error: INSTALLATION FAILED: 1 error occurred:
>         * admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
> Violations details: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume pointerdir in container agent is accessed in write mode; disallowed in Autopilot.","hostPath volume runtimesocketdir used in container agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume cgroups used in container agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume logdockercontainerpath used in container agent uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container process-agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume cgroups used in container process-agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume passwd used in container process-agent uses path /etc/passwd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container process-agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].","hostPath volume runtimesocketdir used in container init-config uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."]}

The only way I am able to get the installation to complete is by setting `logs.enabled: false`. 

However I understand I should set `logs.enabled: true` when I want to get logs from all the containers on my cluster (Ref: https://www.datadoghq.com/blog/gke-autopilot-monitoring/)

**GKE Version:** 1.31.1-gke.2105000

Is there something I am missing here?

I appreciate your help

**Comment by tbavelier** [comment]
I'm not able to reproduce your issue with a very close version (`v1.31.1-gke.1678000`) and a similar chart with exactly the same version:

```shell
╰─❯ helm list
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
dd  	datadog  	4       	2024-12-04 14:45:44.527451 +0100 CET	deployed	datadog-3.81.1	7
╭─ ~/misc/k8s_stuff/autopilot local !5 ?5                                                                                                                      ⎈ gke-timothee-autopilot/datadog 14:46:41
╰─❯ k get nodes
NAME                                                  STATUS   ROLES    AGE   VERSION
gk3-gke-timothee-autopil-nap-lpyqeywm-917c19f8-xdf2   Ready    <none>   40d   v1.31.1-gke.1678000
gk3-gke-timothee-autopilot-pool-2-94ecd417-pck3       Ready    <none>   40d   v1.31.1-gke.1678000
╭─ ~/misc/k8s_stuff/autopilot local !5 ?5                                                                                                                      ⎈ gke-timothee-autopilot/datadog 14:46:44
╰─❯ helm get values dd
USER-SUPPLIED VALUES:
datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: gke-timothee-autopilot
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
    processAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
  ignoreAutoConfig:
  - cilium
  logLevel: info
  logs:
    containerCollectAll: false
    enabled: true
  podAnnotations:
    ad.datadoghq.com/agent.logs: '[{"source": "agent", "service": "agent"}]'
  priorityClassCreate: true
providers:
  gke:
    autopilot: true
╭─ ~/misc/k8s_stuff/autopilot local !5 ?5                                                                                                                      ⎈ gke-timothee-autopilot/datadog 14:46:57
╰─❯ k get pod
NAME                                        READY   STATUS    RESTARTS   AGE
dd-datadog-2chxq                            2/2     Running   0          87s
dd-datadog-cluster-agent-7b7b76d86f-p8sml   1/1     Running   0          87s
dd-datadog-nzhbr                            2/2     Running   0          40s
```

Could you please double-check the indentation of your`values.yaml`/try to use the one I'm using (tweaking the cluster name and other parameters as you see fit) and let us know if it works ? If it doesn't, please open a support ticket (https://www.datadoghq.com/support/) and provide as much details as possible so we can look into reproducing

**Comment by tbavelier** [comment]
> Can you confirm if this is an autopilot constraint?

Indeed, to benefit from privileged access such as mounting hostPath volumes (required for logs collection for instance), you need to use our GCR public repository. This is slightly mentioned in https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-partners#allowlisting-process: 
> Verify that the containers are pulled from the approved location.

When you're not using any of the privileged access, you can use your own repository since it's not checked within the Autopilot admission controller.
