### ISSUE TITLE
datadog.leaderElection does not work properly

### ISSUE THREAD

**Issue by chroju** [DataDog/helm-charts#170]
**Describe what happened:**

`datadog.leaderElection` does not work properly. Setting to `false` does not change the `DD_LEADER_ELECTION` environment variable in cluster-agent.

**Describe what you expected:**

`DD_LEADER_ELECTION` is set to `false` .

**Steps to reproduce the issue:**

Run the following two commands and compare the values of `DD_LEADER_ELECTION` in cluster-agent.

```
$  helm template datadog/datadog --set=datadog.leaderElection=false
$  helm template datadog/datadog --set=datadog.leaderElection=true
```

**Additional environment details (Operating System, Cloud provider, etc):**

N/A

**Comment by ahmed-mez** [comment]
Thank you @chroju for opening this issue, your fix PR has been reviewed.
