### ISSUE TITLE
Documentation should be explicit about `site` value

### ISSUE THREAD

**Issue by hlascelles** [DataDog/helm-charts#188]
We did an install of the chart as described, but all agents were failing:

`UTC | CLUSTER | ERROR | (pkg/forwarder/transaction.go:179 in Process) | API Key invalid, dropping transaction for https://1-3-11-app.agent.datadoghq.com/api/v1/check_run`

It took a long time for us to discover we were missing this value, as we have an EU installation.

```
    datadog:
      site: 'datadoghq.eu'
```

The documentation should be clearer about this setting.

**Comment by Gwojda** [comment]
Thanks man, took me a while to find it too !
