### ISSUE TITLE
Missing images on `public.ecr.aws/datadog` repository

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/helm-charts#198]
**Describe what happened:**
Changing global repository causes `ErrImagePull`

**Describe what you expected:**

The same images present on the default registry are present on the AWS registry

**Steps to reproduce the issue:**
``` 
helm install datadog/datadog --version 2.10.3 --set registry=public.ecr.aws/datadog
```

```
$ docker pull public.ecr.aws/datadog/agent:7.26.0
Error response from daemon: manifest for public.ecr.aws/datadog/agent:7.26.0 not found: manifest unknown: Requested image not found

```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hello,

Sorry for the late reply. `7.26.0` and `7.27.0` `public.ecr.aws/datadog/agent` docker image is now available.

This problem should not append again, `public.ecr.aws/datadog/agent` images are now automatically sync with our other registries.
