### ISSUE TITLE
datadog-cluster-id configmap missing

### ISSUE THREAD

**Issue by matoszz** [DataDog/helm-charts#20]
**Describe what happened:**
container-process-agent.yaml contains a configmap reference to datadog-cluster-id that appears to not get created

**Describe what you expected:**
The configmap to be created by the chart or an init container (or similar)

**Steps to reproduce the issue:**
Enable the "orchestrator" variable and attempt to run the agent; will have configuration errors regarding the missing configmap

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by martinisoft** [comment]
I am seeing this too with the 2.4.30 chart release. Have https://github.com/DataDog/ecommerce-workshop/pull/41 going and can reliably reproduce this issue with a fresh DigitalOcean k8s cluster. Even deleting the HELM chart and re-deploying or upgrading does not resolve the issue and the datadog agent pods never come online. 
![image](https://user-images.githubusercontent.com/724/97371560-7f43e000-187f-11eb-808b-acec222d5465.png)

**Comment by briananstett** [comment]
Although not documented, it appears from the `values.yaml` file that you need to enable the[ ClusterAgent and processAgent](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/values.yaml#LC287:~:text=%23%23%20This%20requires%20processAgent.enabled%20and%20clusterAgent.enabled%20to%20be%20set%20to%20true) in order for the datadog-cluster-id configmap to be made.

**Comment by martinisoft** [comment]
> Although not documented, it appears from the `values.yaml` file that you need to enable the[ ClusterAgent and processAgent](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/values.yaml#LC287:~:text=%23%23%20This%20requires%20processAgent.enabled%20and%20clusterAgent.enabled%20to%20be%20set%20to%20true) in order for the datadog-cluster-id configmap to be made.

When I took it apart with someone else, it was actually the agent image not being correct at the time. I did have the ClusterAgent and ProcessAgent in my values file. Was just an incorrect image that was requesting the wrong thing.

**Comment by jontonsoup** [comment]
was there a solution to this?

**Comment by martinisoft** [comment]
> was there a solution to this?

If you are getting this, go ahead and post your redacted values yaml that you are applying for us to take a look. For me it was an incorrect clusteragent image that I was overriding with the values yaml.

**Comment by clamoriniere** [comment]
hi @matoszz 

From `datadog` chart version `2.9.9`, this issue should be solve. We have update the agent and cluster-agent version which contain a fix this problem.
* agent => `7.26.0`
* cluster-agent => `1.11.0`

Please let us know if it solve the problem for you.

Thanks
Cedric

**Comment by matoszz** [comment]
I'll try and test this out in the next few days

**Comment by ahmed-mez** [comment]
@matoszz I'm closing this as the recent agent, cluster agent and chart versions will not need the configmap anymore.
Feel free to reopen if you still have issues. 

Thanks!
