### ISSUE TITLE
Support kube-state-metrics HA setup

### ISSUE THREAD

**Issue by e96wic** [DataDog/helm-charts#205]
**Describe what happened:**

KSM metrics in DD contain a "host" tag which reports the k8s node which KSM is running on. With multiple replicas of KSM this becomes annoying when trying to calculate sums etc. Because of the host tag, you get a multiple of your actual value per default. Using DD_IGNORE_AUTOCONF=kubernetes_state we can stop scraping metrics from the pods directly. By adding autodiscovery annotations to the k8s-service we get *one* set of metrics. Unfortunately labels like "cluster-name" are also gone, which is not desired.

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by ahmed-mez** [comment]
Hi @e96wic ! 

Thanks for opening this issue, switching to using autodiscovery annotations on the service is indeed a good alternative - note that the official cluster name tag added by the agent is `kube_cluster_name` (not `cluster-name`) and you should be able to see it attached to your ksm metrics out of the box even when using service annotations.

If this comment doesn't help please feel free to [contact](https://www.datadoghq.com/support/) our support team!

Thanks!
