### ISSUE TITLE
containerInclude and containerExclude are not documented

### ISSUE THREAD

**Issue by gajus** [DataDog/helm-charts#212]
Those are discussed [here](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent) and they are in the code, but there is no mention in the documentation of available Helm parameters.

**Comment by roim** [comment]
FWIW the [linked docs](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent) are poorly documented as well. E.g. they state the list is space delimited, but that regexes are comma delimited. There are no examples of multiple regexes, so I have no clue how to do the comma delimiting they mention. Also there's no spec for how the flags behave if you want to filter on both namespace and image (all the examples are just for namespace or just for image), etc.

These flags are really hard to use, even though they are critical to any production cluster--if you want to manage costs.
