### ISSUE TITLE
Helm template with non default namespace generates incorrectly

### ISSUE THREAD

**Issue by tomelfring** [DataDog/helm-charts#217]
**Describe what happened:**
When making an K8S file with `helm template --namespace datadog datadog-agent datadog/datadog`, the resulting files are incorrect.
Some resources do have an namespace set, some don't. For example, the cluster-agent-rbac has an subject to the ServiceAccount in the namespace "datadog", but mentioned ServiceAccount doesn't have an explicit namespace and thus will be created in the current active namespace.

**Describe what you expected:**
I expected the resources which are scoped to a namespace, be defined in given namespace.

**Steps to reproduce the issue:**
- Run `helm template --namespace datadog datadog-agent datadog/datadog`
- Observe the lack of namespace on many resources (ServiceAccounts, Services, Deployments, RoleBindings, Daemonsets, ConfigMaps)

**Additional environment details (Operating System, Cloud provider, etc):**
None

**Comment by afirth** [comment]
this is indeed super weird. means it breaks with kustomize and skaffold.
the ones starting with `default` are affected in a basic install
```
datadog-agent_apps_v1_deployment_datadog-agent-kube-state-metrics.yaml
datadog-agent_kubernetes-client.io_v1_externalsecret_datadog-agent-cluster-agent.yaml
datadog-agent_kubernetes-client.io_v1_externalsecret_datadog-agent.yaml
datadog-agent_v1_serviceaccount_datadog-agent-kube-state-metrics.yaml
datadog-agent_v1_service_datadog-agent-kube-state-metrics.yaml
default_apps_v1_daemonset_datadog-agent.yaml
default_apps_v1_deployment_datadog-agent-cluster-agent.yaml
default_v1_configmap_datadog-agent-installinfo.yaml
default_v1_serviceaccount_datadog-agent-cluster-agent.yaml
default_v1_serviceaccount_datadog-agent.yaml
default_v1_service_datadog-agent-cluster-agent.yaml
```
