### ISSUE TITLE
If Agent Tag is not specified, GCR tries to default to 1.19

### ISSUE THREAD

**Issue by JacobWeyer** [DataDog/helm-charts#222]
https://github.com/DataDog/helm-charts/blob/b08b1771cc7544bf590581388804fee7af2a4ab3/charts/datadog/values.yaml#L664

```  
Normal   Scheduled  56s                default-scheduler  Successfully assigned datadog/datadog-cluster-agent-56596dc7df-s8fzv to ip-10-20-149-213.us-west-2.compute.internal
  Normal   BackOff    24s (x3 over 54s)  kubelet            Back-off pulling image "gcr.io/datadoghq/agent:1.9.0"
  Warning  Failed     24s (x3 over 54s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    9s (x3 over 55s)   kubelet            Pulling image "gcr.io/datadoghq/agent:1.9.0"
  Warning  Failed     9s (x3 over 55s)   kubelet            Failed to pull image "gcr.io/datadoghq/agent:1.9.0": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/datadoghq/agent:1.9.0 not found: manifest unknown: Failed to fetch "1.9.0" from request "/v2/datadoghq/agent/manifests/1.9.0".
  Warning  Failed     9s (x3 over 55s)   kubelet            Error: ErrImagePull
```

**Comment by clamoriniere** [comment]
Hello @jacobWeyer,

Thanks for reporting this issue.

Looking at the first log line that you have provied, it seams to be related to the "cluster-agent" deployment dans not the `agent` deployed on every node thank to a daemonset. Could you confirm it? 

If it is the case, the `cluster-agent` should use another image (default: `gcr.io/datadoghq/cluster-agent:1.11.0`). And it configuration is coming from https://github.com/DataDog/helm-charts/blob/b08b1771cc7544bf590581388804fee7af2a4ab3/charts/datadog/values.yaml#L418

Could youp provide the version of the helm chart that you are using and, run an `helm template` command to check what is the generate `container.image` value generated for the cluster-agent container?

Thanks for your help.

**Comment by JacobWeyer** [comment]
yeah you're right. We mixed up the images.
