### ISSUE TITLE
"failed to generate seccomp security options for container" when installing datadog chart

### ISSUE THREAD

**Issue by loganfsmyth** [DataDog/helm-charts#225]
**Describe what happened:**

I just went to deploy our backend, and I'm getting a `CreateContainerError` starting the datadog container.

`kubektl describe pod datadog-XXX` says the following:

```
  Warning  Failed     11m (x4 over 11m)   kubelet            Error: failed to generate security options for container "system-probe": failed to generate seccomp security options for container: invalid character '#' looking for beginning of value
```

I'm guessing this is from https://github.com/DataDog/helm-charts/pull/224#pullrequestreview-646324685 since searching this repo for `seccomp` points to that as a recent PR.

**Comment by gcavalcante8808** [comment]
I Can confirm this, using 2.11.4.

Rollback to 2.11.3 seems good enough for me as I don't need to kubectl exec into agent container.

**Comment by clamoriniere** [comment]
Hello, 
Sorry for the trouble, the PR ##227 will fix the issue by removing the comment in the json file.
the chart 2.11.5 will fix the problem.
