### ISSUE TITLE
containerInclude/containerExclude `image` tags broken in major image registries

### ISSUE THREAD

**Issue by roim** [DataDog/helm-charts#232]
**Describe what happened:**
When using `containerInclude` in the helm values, the following declaration collects logs/custom metrics from the listed containers, but *does not* collect standard integrations (eg the container does not appear in Datadog's "Infrastructure>Containers" tab:

```
image:(docker\.io/myCompany|k8s\.gcr\.io/ingress-nginx).*
```

The following declaration collects logs/metrics and also standard integrations:

```
image:.*(myCompany|ingress-nginx).*
```

We use cert-manager, and I noticed that this particular declaration also collects everything:

```
image:(quay\.io/jetstack/cert-manager).*
```

So having major registries such as `docker.io` and `k8s.gcr.io` in your image filters makes only some of the data to be collected by the agent, but some other registries such as `quay.io` work fine.

Note that while I have tested prefixing a company with `.*`, and it does collect everything, I haven't tested just `image:(myCompany).*`--that might not collect application logs, just standard integrations.

**Describe what you expected:**

Filtering on `docker.io/myCompany` should work across all data collection since that's the official name Kubernetes gives to the container's image.

**Steps to reproduce the issue:**

Trivial from above.

**Additional environment details (Operating System, Cloud provider, etc):**

Amazon Linux, AWS, EKS.

**Comment by celenechang** [comment]
Hi @roim , thank you for reporting! I wasn't able to reproduce the issue and would like to investigate further. Do you mind emailing support@datadoghq.com and referencing this github issue? Once a ticket is opened an agent [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7) can be sent and I can dig in. Thanks!

**Comment by roim** [comment]
Hi @celenechang, sorry, this was a while ago and it would take me some time to try another repro. I think the workaround I described here is easy enough for anyone else finding this issue (and hopefully they could link the info you need), so feel free to close the task. Thanks!
