### ISSUE TITLE
Cilium policy's are not working

### ISSUE THREAD

**Issue by martijnvdp** [DataDog/helm-charts#246]
**Describe what happened:**
Cilium policys are not working

after enabling the options:

  networkPolicy:

    # datadog.networkPolicy.create -- If true, create NetworkPolicy for all the components

    create: true

    # datadog.networkPolicy.flavor -- Flavor of the network policy to use.
    # Can be:
    # * kubernetes for networking.k8s.io/v1/NetworkPolicy
    # * cilium     for cilium.io/v2/CiliumNetworkPolicy
    flavor: cilium

gives several errors :
error validating data: ValidationError(CiliumNetworkPolicy.specs[4].ingress[0]): unknown field "toEndpoints" in io.cilium.v2.CiliumNetworkPolicy.specs.ingress

**Describe what you expected:**

**Steps to reproduce the issue:**
enable network policys with flavor cilium

**Additional environment details (Operating System, Cloud provider, etc):**

The cilium policy contains ingress statements with **toEndpoints** instead of **fromEndpoints**
and some wrong formatting and missing services

I've made a pr to fix this https://github.com/DataDog/helm-charts/pull/245

**Comment by nairb** [comment]
I just tried setting this up and am seeing the exact same issue.

**Comment by martijnvdp** [comment]
The fix is merged so you could try it again

**Comment by martijnvdp** [comment]
https://github.com/DataDog/helm-charts/pull/245
