### ISSUE TITLE
YAML parse error on datadog/templates/daemonset.yaml

### ISSUE THREAD

**Issue by RaoulBrueckler** [DataDog/helm-charts#255]
**Describe what happened:**
I want to deploy datadog to a GKE Autopilot Cluster -> Instructions from here https://www.datadoghq.com/blog/gke-autopilot-monitoring/

Command used:
- helm install <RELEASE_NAME> \
    --set datadog.apiKey=<DATADOG_API_KEY> \
    --set datadog.appKey=<DATADOG_APP_KEY> \
    --set clusterAgent.enabled=true \
    --set clusterAgent.metricsProvider.enabled=true \
    --set providers.gke.autopilot=true \
    --set datadog.logs.enabled=true \
    --set datadog.apm.enabled=true \
    --set datadog.kubeStateMetricsEnabled=false \
    --set datadog.kubeStateMetricsCore.enabled=true \
    datadog/datadog
 
Got this Error:
YAML parse error on datadog/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 51: mapping values are not allowed in this context

**Describe what you expected:**
Deploy Datadog on GKE Autopilot

**Steps to reproduce the issue:**
- helm repo add datadog https://helm.datadoghq.com
- helm repo add stable https://charts.helm.sh/stable
- helm repo update
- helm install <RELEASE_NAME> \
    --set datadog.apiKey=<DATADOG_API_KEY> \
    --set datadog.appKey=<DATADOG_APP_KEY> \
    --set clusterAgent.enabled=true \
    --set clusterAgent.metricsProvider.enabled=true \
    --set providers.gke.autopilot=true \
    --set datadog.logs.enabled=true \
    --set datadog.apm.enabled=true \
    --set datadog.kubeStateMetricsEnabled=false \
    --set datadog.kubeStateMetricsCore.enabled=true \
    datadog/datadog

**Additional environment details (Operating System, Cloud provider, etc):**
- Kuberenetes Version 1.19.9-gke.1400 Regular
- Datadog Helm Chart Version 2.13.1

**Comment by clamoriniere** [comment]
Hi @RaoulBrueckler 

Thanks for opening this issue. I was able to reproduce it. #256 should fix it.

**Comment by clamoriniere** [comment]
`datadog/datadog` chart version `2.13.2` has been release with the fix.

**Comment by RaoulBrueckler** [comment]
Thanks a lot :) it works
