### ISSUE TITLE
Missing tags on metrics when new KubeStateCore integration is enabled

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/helm-charts#319]
**Describe what happened:**
extra labels are missing from the [`KubernetesStateCore` metrics](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#migration-from-kubernetes_state-to-kubernetes_state_core)

![image](https://user-images.githubusercontent.com/1277613/124920895-ba420a00-dfef-11eb-9f25-25b0daee5bbd.png)

**Describe what you expected:**
Metrics have the same tags, including the deployment tags when using `KubeStateCore` integration instead of `kube-state-metrics` exporter
https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm

**Steps to reproduce the issue:**
We are deploying with the following `values` chart version `2.18.3`
```
clusterAgent:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 150Mi
    requests:
      cpu: 25m
      memory: 100Mi
  token: <TOKEN>
datadog:
  apiKey:  <KEY>
  apm:
    enabled: true
  clusterChecks:
    enabled: true
  dogstatsd:
    nonLocalTraffic: true
    useHostPort: true
  kubeStateMetricsCore:
    enabled: true
    ignoreLegacyKSMCheck: true
  kubeStateMetricsEnabled: false
  logs:
    enabled: false
  processAgent:
    enabled: true
    processCollection: true
  site: datadoghq.com
  tags:
  - cluster_name:<NAME>
  - env:<STACK_NAME>-develop
  - stack_name:<STACK_NAME>
  - stack_type:develop
registry: public.ecr.aws/datadog
```
**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.20
```
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

reported on #304 too

**Comment by ahmed-mez** [comment]
Hi @carlosjgp thanks for reporting this and sorry for the trouble! 

We're aware of this issue and a fix will be released in the next agent and cluster agent versions!

**Comment by shanegibbs** [comment]
We are having this issue as well. When is the next version (with the fix) due to be released please?

**Comment by caleb15** [comment]
@ahmed-mez just wanted to confirm now that the chart is updated to agent image v7.31.0 and cluster image v1.15.0 is this fixed?

**Comment by carlosjgp** [comment]
Tags are still missing because `DD_TAGS` env var is not added to `cluster-agent` unless metrics provider is enabled
https://github.com/DataDog/helm-charts/blob/dbbbc724f870d8de69ad519dee3526c461d45c34/charts/datadog/templates/cluster-agent-deployment.yaml#L132

**Comment by carlosjgp** [comment]
just for completeness...

This is still not working I've opened an issue on the [integrations core project](https://github.com/DataDog/integrations-core/issues/10205) because I understand the problem is there...?
