### ISSUE TITLE
Missing network policies

### ISSUE THREAD

**Issue by robwithhair** [DataDog/helm-charts#33]
**Describe what happened:**
Deployed to default namespace but could not communicate with datadog over the network

**Describe what you expected:**
Network policies to be created alongside the other infrastructure to allow communication where necessary between pods and with the outside world.

**Steps to reproduce the issue:**
Deploy with default deny all networking policy in same namespace and with some kubernetes networking set up such as calico.  

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS with Calico installed and set up.

**Comment by robwithhair** [comment]
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by vboulineau** [comment]
Hey @robwithhair,

We've merged NetworkPolicy support in our chart. Feel free to use it and provide feedback if something's not right!
