### ISSUE TITLE
Does not configure the cluster name for the cluster check runner pods

### ISSUE THREAD

**Issue by deadok22** [DataDog/helm-charts#337]
Setting `datadog.clusterName` doesn't affect the cluster check runner pods. That can result in different agents running with different values of cluster name.

In my particular case, setting `datadog.clusterName` broke the tagging for some `kubernetes_state` metrics. E.g. `kubernetes_state.node.cpu_allocatable`.

**Comment by clamoriniere** [comment]
Hi @deadok22 

Thanks for reporting this issue.

We confirm that the "DD_CLUSTER_NAME" envvar is missing on the cluster-check pods deployment. 

We will work on a fix soon.

Cheers
Cedric

**Comment by deadok22** [comment]
This was fixed in https://github.com/DataDog/helm-charts/pull/687.
