### ISSUE TITLE
Current default agent tag has a know bug

### ISSUE THREAD

**Issue by dpp23** [DataDog/helm-charts#354]
The current `datadog` chart has a default version of the agent pinned to `7.30.1` which suffers from this bug https://github.com/DataDog/datadog-agent/issues/8895

It should probably be downgraded or be bumped as soon as `7.30.1` is available. We lost a large portion of our metrics in the last chart version bump because of this.

**Comment by caleb15** [comment]
The latest version of the helm chart is now on 7.31 FYI: https://github.com/DataDog/helm-charts/blob/7879dd1f56d281540a3274a003ef9dabd3579ff3/charts/datadog/values.yaml#L748

**Comment by L3n41c** [comment]
The default version of the datadog agent in the latest chart is now `7.32.1`:
https://github.com/DataDog/helm-charts/blob/959c136e87599d0a6ce6f09031677745511d0d08/charts/datadog/values.yaml#L779
