### ISSUE TITLE
Consider using alternative source for kubeval schemas

### ISSUE THREAD

**Issue by spencergilbert** [DataDog/helm-charts#360]
[instrumenta/kubernetes-json-schema](https://github.com/instrumenta/kubernetes-json-schema) is noticeably out of date at this point, with the last commit to master landing in April of 2020, this puts the latest provided Kubernetes version at 1.18.1.

As an alternative there is [yannh/kubernetes-json-schema](https://github.com/yannh/kubernetes-json-schema) which is self-updating and currently up-to-date.

It's a trivial change to update the schema source (see: [here](https://github.com/timberio/helm-charts/blob/master/.github/kubeval.sh#L6)).

This would allow for the Helm charts to be evaluated against more, and more recent versions of Kubernetes.

**Comment by wyardley** [comment]
I added that back in #664 FWIW
Also have just opened #1199 which proposes moving to `kubeconform` entirely.
