### ISSUE TITLE
Support dogstatsd_mapper_profiles

### ISSUE THREAD

**Issue by MikeMarcheseSpin** [DataDog/helm-charts#388]
dogstatsd_mapper_profiles should be added into the dogstsd config section to support this: https://docs.datadoghq.com/developers/dogstatsd/dogstatsd_mapper/

**Comment by icelynjennings** [comment]
If `agents.useConfigMap` is `true`, can this be achieved by appending lines to `agents.customAgentConfig`?

As a follow-up question, does `agents.customAgentConfig` APPEND its map to each datadog container's `datadog.yaml` or does it REPLACE all `datadog.yaml` contents with `agents.customAgentConfig`?

**Comment by nwhobart** [comment]
@icelynjennings would you be willing to share your configuration? also what happened to you `datadog.yaml` file when you made these changes in the values.yaml file?
