### ISSUE TITLE
Missing configuration for DD_CHECKS_TAG_CARDINALITY env variable

### ISSUE THREAD

**Issue by Niksko** [DataDog/helm-charts#39]
**Describe what happened:**

While attempting to get the `pod_name` tag added to pods, I realised that setting the `DD_CHECKS_TAG_CARDINALITY` env variable to a value of `orchestrator` is what allows this. There isn't currently a helm chart option to configure this value.

**Describe what you expected:**

A helm chart option to configure this value.

**Steps to reproduce the issue:**

Not really relevant, other than the fact that I tried using the `datadog.dogstatsd.tagCardinality` flag to enable this, but it configures something else.

**Additional environment details (Operating System, Cloud provider, etc):**

Latest helm chart version

**Comment by BenConstable** [comment]
You can use `datadog.env` to set this (although I do agree that a more explicit Chart parameter would perhaps be nice!):

```yaml
datadog:
  env:
    - name: DD_CHECKS_TAG_CARDINALITY
      value: "true"
```
