### ISSUE TITLE
[charts/datadog] Liveness probe failures

### ISSUE THREAD

**Issue by caleb15** [DataDog/helm-charts#421]
**Describe what happened:**
Some days we receive multiple liveness probe failures, around 5 or so. They come from the datadog agent or the datadog cluster agent.

**Describe what you expected:**
Very few liveness probe failures (a couple a week is fine). We have alerts setup for liveness probe failures so the less failures, the less alerts, and the less alerts the better. We could lower the sensitivity of our alerting, but then our response time goes down or we might not realize a deployment failed. Hopefully there is a improvement that can be made in the Datadog codebase.

**Steps to reproduce the issue:**
1. Deploy datadog chart v2.22.1 to a cluster that gets deployed to / scaled up / scaled down daily.
2. Wait.

**Additional environment details (Operating System, Cloud provider, etc):**
We're using EKS and Kubernetes v1.21

Example events:

The Datadog cluster agent mostly fails due to 500 error.
```
Warn: Liveliness probe failed on env:cloud20,name:datadog-cluster-agent-64f8f59666-wwx98
1 Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 500
1 Unhealthy: Liveness probe failed: HTTP probe failed with statuscode: 500

Events emitted by the kubelet seen at 2021-10-16 00:50:42 +0000 UTC since 2021-10-16 00:50:42 +0000 UTC  @slack-15Five-devops-alerts-cloud20
Number of events matching excluded_tags:namespace:kube-system priority:all sources:kubernetes Liveness probe failed status:warning on env:cloud20,name:datadog-cluster-agent-64f8f59666-wwx98 was > 0.0 during the last 2m
Tags
env:cloud20, name:datadog-cluster-agent-64f8f59666-wwx98
```

The Datadog agent fails either due to "no route to host" or due to "connection refused":
```
Warn: Liveliness probe failed on env:cloud20,name:datadog-rwg9w
1 Unhealthy: Liveness probe failed: dial tcp 10.20.36.27:8126: connect: no route to host
1 Unhealthy: Liveness probe failed: Get &quot;http://10.20.36.27:5555/live&quot;: dial tcp 10.20.36.27:5555: connect: no route to host
1 Unhealthy: Readiness probe failed: Get &quot;http://10.20.36.27:5555/ready&quot;: dial tcp 10.20.36.27:5555: connect: no route to host

Events emitted by the kubelet seen at 2021-10-16 00:50:59 +0000 UTC since 2021-10-16 00:50:59 +0000 UTC  @slack-15Five-devops-alerts-cloud20
Number of events matching excluded_tags:namespace:kube-system priority:all sources:kubernetes Liveness probe failed status:warning on env:cloud20,name:datadog-rwg9w was > 0.0 during the last 2m
Tags
env:cloud20, name:datadog-rwg9w
Notified
@slack-15Five-devops-alerts-cloud20
```

**Comment by SteveJ-IT** [comment]
Same issue here

**Comment by caleb15** [comment]
I opened up a Datadog support ticket but never got around to enabling debug mode and sending a flare. It stopped becoming a issue for us anyways, not sure why. @SteveJ-IT I suggest you open up a support ticket

**Comment by levan-m** [comment]
Resolving as the issue was resolved for the original requester and haven't received any updated for the other report.
