### ISSUE TITLE
APM enabled over TCP even if `datadog.apm.portEnabled` is `false`

### ISSUE THREAD

**Issue by jakubfijalkowski** [DataDog/helm-charts#423]
**Describe what happened:**
After updating to `datadog` chart >= 2.21, our agent started to collect APM traces over host port even when `datadog.apm.enabled` (the old `datadog.apm.portEnabled`) was set to `false`.

**Describe what you expected:**
APM are not collected.

**Steps to reproduce the issue:**
Deploy `datadog` >= 2.21 chart with default configuration (that suffices). The pod will accept and process APM traffic over default host port.

**Additional environment details (Operating System, Cloud provider, etc):**
Azure Kubernetes Services, 1.22.2, Azure CNI without Azure Network Policy

**Investigation**
After splitting `datadog.apm.enabled` into `datadog.apm.socketEnabled` and `datadog.apm.portEnabled` in v2.21, the DaemonSet started deploying the `trace-agent` if `socketEnabled = true && portEnabled = false`. Unfortunately, the `trace-agent` exposes host port for APMs even if the `portEnabled` is set to `false` as [you can see here](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_container-trace-agent.yaml#L17-L21). This makes it accept traces over TCP even if we explicitly disable it.

This would not happen if network policies (or PSPs) are deployed, as these block the port if disabled. Nevertheless, these are not deployed by default (and would not solve the issue for me, as I don't have network policies enabled and PSPs are being deprecated).

**Comment by clamoriniere** [comment]
Hello @jakubfijalkowski 

Sorry if encounter issue with this chart update.
We will provide a fix soon.

**Comment by jakubfijalkowski** [comment]
Hi @clamoriniere ! No worries, it's better this way than the other way around. :)
