### ISSUE TITLE
Avoid deprecated API versions on YAML definitions for Kubernetes 1.21

### ISSUE THREAD

**Issue by michelzanini** [DataDog/helm-charts#436]
**Describe what happened:**

When using Kubernetes 1.21 we get these warnings all the time:

```
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

```
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

This is because the APIs above have now migrated out of beta.

**Describe what you expected:**

Expected is on older Kubernetes versions it uses the v1beta1 APIs, but on Kubernetes 1.21+ it uses the new stable versions to avoid the warnings messages.

It might be possible to this using the Helm function to check API versions available `Capabilities.APIVersions.Has`.
It might be worth trying this function to see if it will work?

**Steps to reproduce the issue:**

Run the helm chart on 1.21 and look at the logs.

**Comment by clamoriniere** [comment]
Thanks for opening this issue.

I'm adding this improvement in our backlog.
