### ISSUE TITLE
Enabling admission controller should turn on clusterAgent HA mode

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/helm-charts#438]
**Describe what happened:**
I have the admission controller turned on.

When I upgraded my cluster from 1.20 to 1.21 this morning, several pods came alive without `DD_AGENT_HOST` injected.  I discovered that this is because my `clusterAgent` was only configured with a single replica and no PDB, so it had downtime.

It is not called out in the documentation that the `admissionController` is just a reference to the `clusterAgent` itself.  And since I rely on these injected values, I need the controller (hence the `clusterAgent`) in HA mode.

**Describe what you expected:**
When I turn on the `admissionController`, the `clusterAgent` should be set (or at least advised to be set) to HA mode.  `clusterAgent` should always have one replica running so that `DD_AGENT_HOST` is injected.  Consider enabling the PDB with the `admissionController`.

**Steps to reproduce the issue:**
Enable cluster agent with default config.  Enable admission controller with default config.  Note one replica and lack of other HA characteristics (pdb, deployment maxUnavailable, etc).

**Additional environment details (Operating System, Cloud provider, etc):**
EKS

**Comment by clamoriniere** [comment]
Hello @jcogilvie 

Thanks you for reporting this issue, indeed the chart should provide a PodDisruptionBudget  for every deployment (`cluster-agent` and `cluster-check-runner`)

We could also add a warning message when the `admissionController` or the `external metrics server` are enabled to advise the user to set the cluster-agent deploymen `replicas` value to `2`.

We will work soon on a fix.
