### ISSUE TITLE
typo 'cluster_checks' in cluster-agent-confd-configmap.yaml

### ISSUE THREAD

**Issue by danemiller** [DataDog/helm-charts#460]
There's a typo that prevents kubeStateMetricsCore from executing on the cluster check runners.

Should be "cluster_check" not "cluster_checks": https://github.com/DataDog/helm-charts/blob/20748841652b085e12df9b85fc7f0cfbf9f4b16b/charts/datadog/templates/cluster-agent-confd-configmap.yaml#L18

Here's the datadog-agent source code that expects this field to be called "cluster_check" https://github.com/DataDog/datadog-agent/blob/00aafcde7f12fd4e6f396f427ccbe962298b77c2/pkg/autodiscovery/providers/file.go#L28

Here's the error from cluster agent's logs:
```
2021-12-09 00:02:17 UTC | CLUSTER | WARN | (pkg/autodiscovery/providers/file.go:280 in GetIntegrationConfigFromFile) | reading config file /etc/datadog-agent/conf.d/kubernetes_state_core.yaml.default: yaml: unmarshal error
line 1: field cluster_checks not found in type providers.configFormat
```

**Comment by clamoriniere** [comment]
Hi @danemiller 
Thanks for catching this typo. Indeed it should be `cluster_check`.
