### ISSUE TITLE
DD_CONTAINER_EXCLUDE_LOGS excludes matching like namespaces

### ISSUE THREAD

**Issue by sadok-f** [DataDog/helm-charts#471]
**Describe what happened:**
We're using DD agent in our k8s cluster hosted on AWS, we have the following exclude rules:
```
DD_CONTAINER_EXCLUDE_LOGS="kube_namespace:logging kube_namespace:monitoring"
```
We want to exclude logs from `logging` and `monitoring` namespaces, the issue appears for other namespaces called `processing-logging` and `processing-monitoring` as we want to fetch logs from those namespaces as well, but it seems 
DD-agent configuration excludes them because of the `DD_CONTAINER_EXCLUDE_LOGS` flag.

**Describe what you expected:**
Only logs from namespaces that match exactly the flag `DD_CONTAINER_EXCLUDE_LOGS` should be excluded, unless there's another workaround for this,

**Steps to reproduce the issue:**
```
DD_CONTAINER_EXCLUDE_LOGS="kube_namespace:login"
namespace logging : pod test_pod_1
namespace processing-logging: : pod test_pod_2
namespace test : pod test_pod_3
```
Only logs from the test namespace is appearing in the DD dashboard.

**Additional environment details (Operating System, Cloud provider, etc):**

Agent version: `Agent 7.32.1 - Commit: 52f034f - Serialization version: v4.85.0 - Go version: go1.16.7`
Datadog Helm version: `## 2.27.5`
Thank you :)

**Comment by clamoriniere** [comment]
Hi @sadok-f,

the value behind the `kube_namespace` key is a regex pattern. 
the Datadog agent is build in golang, but its regex library doesn't enforce strong match by default.

So if your goal is only to exclude the `logging` namespace, the value should be `kube_namespace:^logging$` (same for `monitoring`)

Another remark: 
The chart expose two options `datadog.containerExcludeLogs` `datadog.containerIncludeLogs` to ease the setting of these parameters. You should use it.

**Comment by sadok-f** [comment]
Many thanks @clamoriniere !
that worked perfectly.

**Comment by sebasrincon** [comment]
How can I exclude metrics using containerExcludeMetrics as well?

**Comment by Sandeepb-nextcar** [comment]
how can i include multiple namespaces? having issues when passing multiple namespaces ?
kube_namespace:^logging$ kube_namespace:^monitoring$

**Comment by clamoriniere** [comment]
Hi @Sandeepb-nextcar 

As documented [here](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tabs=containerizedagent#exclude-containers)

```yaml
datadog:
  containerExclude: `kube_namespace:^logging$ kube_namespace:^monitoring$`
```

or simpler if you want to exclude on `logging` and `monitoring` namespaces.

```yaml
datadog:
  containerExclude: `kube_namespace:logging kube_namespace:monitoring`
```

Could you check the if the provided configuration has been properly parsed by the agent with

```console
kubectl exec -it <datadog-agent-pod-name> -- agent config
```

Thanks
