### ISSUE TITLE
Cluster Agent PDB blocks scaledown

### ISSUE THREAD

**Issue by omnibs** [DataDog/helm-charts#49]
**Describe what happened:**

I flipped the flag to create a PDB for the Cluster Agent.

It created a PDB with `minAvailable: 1`.

The cluster agent runs a single pod.

Cluster Autoscaler won't ever downscale a node where Cluster Agent lives, and I'll have to delete the pod manually to drain nodes for maintenance.

I saw no flags to allow running Cluster Agent with more than a single Pod.

**Describe what you expected:**

One of:
* The ability to run more than one cluster agent, with leader election or something, so I can respect the bundled PDB and still downscale/drain
* Some documentation on why the Cluster Agent's PDB prevents scaledowns
* No PDB, if Cluster Agent scaledowns aren't the end of the world

**Steps to reproduce the issue:**

`clusterAgent.createPodDisruptionBudget = true`

Try to drain a node where Cluster Agent is installed.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by vboulineau** [comment]
Hi @omnibs,

There is already the `clusterAgent.replicas` option to set the number of Cluster Agent PODs. It allows the Cluster Agent to work in HA mode with leader election.

Indeed, `clusterAgent.createPodDisruptionBudget` option should only be set when `clusterAgent.replicas` > 1

**Comment by omnibs** [comment]
Oh cool, sorry for not spotting it!

Thanks for following up =]
