### ISSUE TITLE
Unable to create security context constraint for cluster agent

### ISSUE THREAD

**Issue by gpsouza93** [DataDog/helm-charts#499]
**Describe what happened:**
Unable to create security context constraint for cluster agent due to invalid values for parameters allowedCapabilities and defaultAddCapabilities using Helm 3.

**Describe what you expected:**
Security context constraint for cluster agent successfully created

**Steps to reproduce the issue:**
1 - Set parameter clusterAgent.podSecurity.securityContextConstraints.create to true in values.yaml used to install Datadog Agent Helm Chart
2 - Try to install or upgrade Datadog on OpenShift cluster using latest chart version
3 - Helm returns invalid value error for parameters allowedCapabilities and defaultAddCapabilities

**Additional environment details (Operating System, Cloud provider, etc):**
File https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/cluster-agent-scc.yaml sets "null" as default value for both parameters. The value is not accepted. Helm error indicates value should be "[]" instead of "null".

Helm: v3.7.2
OpenShift: 3.11

**Comment by gpsouza93** [comment]
Hello, I have tested again with v2.28.9 after the commit. Now I receive another error suggesting that the parameters are missing.

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(SecurityContextConstraints): missing required field "defaultAddCapabilities" in com.github.openshift.api.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints): missing required field "allowedCapabilities" in com.github.openshift.api.security.v1.SecurityContextConstraints]

**Comment by clamoriniere** [comment]
hello, 
I'm not able to reproduce you issue with openshift 3.11 (minishift). 
do you have a specific admission controller validation on you openshift cluster?

**Comment by gpsouza93** [comment]
No, I do not have any custom admission controller validation on the cluster. But the fields "defaultAddCapabilities" and "allowedCapabilities" are marked as required on OpenShift 3.11 API Reference documentation. For OpenShift > 4.6, they are no longer required.
https://docs.openshift.com/container-platform/3.11/rest_api/security_openshift_io/securitycontextconstraints-security-openshift-io-v1.html
https://docs.openshift.com/container-platform/4.6/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html
