### ISSUE TITLE
how can i disable and remove the trace-agent container from the agent pod using values.yml? we are not using it. 

### ISSUE THREAD

**Issue by roimor** [DataDog/helm-charts#503]
**Describe what happened:**

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by L3n41c** [comment]
Hello @roimor,

You can remove the `trace-agent` container by setting `datadog.apm.socketEnabled` to `false`:
```yaml
datadog:
  apm:
    socketEnabled: false
```

Please see https://github.com/DataDog/helm-charts/tree/main/charts/datadog#enabling-apm-and-tracing

**Comment by roimor** [comment]
thank you! that worked!
