### ISSUE TITLE
Datadog chart annotations cause helm-diff to always show changes

### ISSUE THREAD

**Issue by HarrisonTotty** [DataDog/helm-charts#512]
**Describe what happened:**
When managing the datadog chart via [Helmsman](https://github.com/Praqma/helmsman), I noticed that Helmsman would perform an upgrade of the datadog chart despite no changes to the chart's `values.yaml` or Helmsman's Desired State File. Helmsman determines whether a release should be upgraded via a call to the [helm-diff](https://github.com/databus23/helm-diff) plugin. This call can be replayed via something akin to the following:
```bash
helm diff --suppress-secrets upgrade datadog datadog/datadog --version 2.27.6 --namespace datadog -f .helmsman-tmp/tmp3378220818/6940149values.yaml -C 2
```
When doing so I notice that each time the above command is run (between _actual_ deployments), the `checksum/clusteragent_token` and `checksum/api_key` annotations of the agent `DaemonSet` and `Deployment` objects change values, thus resulting in `helm-diff` claiming there to be a change. Unfortunately, while Helmsman does allow the user to pass arbitrary flags to `helm-diff` and `helm-diff` provides a `--suppress` CLI option for disabling a particular kubernetes API object (like `DaemonSet`), there is currently no way to instruct `helm-diff` to ignore sub-paths of rendered objects.

The problem itself seems to arise from computations like these:
```yaml
checksum/clusteragent_token: {{ include (print $.Template.BasePath "/secret-cluster-agent-token.yaml") . | sha256sum }}
```

See also Praqma/helmsman#629

**Describe what you expected:**
A datadog chart release should not produce changes via `helm-diff`, or have the option to disable the offending annotations.

**Steps to reproduce the issue:**
1. Install the chart via Helm or Helmsman.
2. Run a similar `helm diff` to the one above.

**Additional environment details (Operating System, Cloud provider, etc):**
OS: Arch Linux (5.15.13-arch1-1)
kubectl client: 1.23.1
Kubernetes Cluster: Amazon EKS
Kubernetes Cluster Version: 1.21.2
Helm Version: 3.7.2
Helmsman Version: 3.8.0
Helm Diff Plugin Version: 3.3.2
Datadog Chart Verison: 2.27.6

**Comment by clamoriniere** [comment]
Hi @HarrisonTotty 

this checksum contains the `clusterAgent.token` option. To ease Datadog chart onboarding, we have implemented a "token" generator that will populate this field if the user didn't provide a value. 

I suspect that you are in that case. An so each time the you run an "helm template|install" the generated token is different which lead to a different checksum each time.

The 2 options to solve this issue are:
1. provide in the `values.yaml` file a value for `clusterAgent.token`.
2. store the `token` in a secret and provide the name to the token to the installation with the parameter `clusterAgent. tokenExistingSecret`. The secret needs to be in the same `namespace` and the "key" inside the secret needs to be `token`.

Please lets us know if it solve the issue.

**Comment by HarrisonTotty** [comment]
Yep! Setting that value fixed things! Thanks for the help :)
