### ISSUE TITLE
Datadog-cluster-agent secrets access still broken 

### ISSUE THREAD

**Issue by ghost** [DataDog/helm-charts#516]
continuing from: https://github.com/DataDog/helm-charts/issues/479

The env in the pod definitely says: DD_SECRET_BACKEND_COMMAND: /readsecret_multiple_providers.sh
But the datadog_cluster_agent role isn't touched.
And the datadog_cluster_agent role DEFINITELY is based on 2.28.13. But no secret access. 

Hi @frankbranham 

Thanks for opening this issue and sorry for the trouble.

We acknowledge the issue and we'll try to get this fixed as soon as we can. Ideally, we won't be adding rbacs to get secrets unless `DD_SECRET_BACKEND_COMMAND=/readsecret_multiple_providers.sh` is configured.

_Originally posted by @ahmed-mez in https://github.com/DataDog/helm-charts/issues/479#issuecomment-995950175_

**Comment by ahmed-mez** [comment]
Closing in favour of https://github.com/DataDog/helm-charts/issues/479
