### ISSUE TITLE
cluster-agent podAntiAffinity prevents helm upgrade on 1-node cluster

### ISSUE THREAD

**Issue by abe-winter** [DataDog/helm-charts#517]
**Describe what happened:**
When running `helm upgrade` on a single-node cluster, the podAntiAffinity rule for the cluster-agent deployment, [here](https://github.com/DataDog/helm-charts/blob/f1820b74bc1ec647c544b26f6d69e1ef01ce9974/charts/datadog/templates/cluster-agent-deployment.yaml#L327-L338), makes it impossible to schedule a new cluster-agent pod.

This causes helm to hang and then time out.

**Describe what you expected:**
`helm upgrade` should succeed.

**Steps to reproduce the issue:**
`helm install` datadog on a single-node cluster, then `helm upgrade`. The install will work, the upgrade will hang.

**Additional environment details (Operating System, Cloud provider, etc):**
- Kube 1.21
- EKS
- datadog helm version 2.28.11

**Workarounds**
- initially I worked around this by manually deleting the existing cluster-agent pod during `helm upgrade`. This works, but you're flipping a coin that the new version gets scheduled first. Rarely, the old pod version has to be deleted several times.
- then I set `clusterAgent: { affinity: { podAntiAffinity: null } }` in my helm values, which seemed to patch the problem. (if you do this, you will have to delete the old cluster-agent pod one last time as kube respects the anti-affinity rule from the old, running pod)

**Possible fix**
I didn't test this, but it's possible you can patch by changing `requiredDuringSchedulingIgnoredDuringExecution` to `preferredDuringSchedulingIgnoredDuringExecution` in the template, albeit with changes to the 'hot standby' guarantee this affinity rule is designed to provide.

https://github.com/DataDog/helm-charts/blob/f1820b74bc1ec647c544b26f6d69e1ef01ce9974/charts/datadog/templates/cluster-agent-deployment.yaml#L327-L338

Another option could be to only set the anti-affinity rule when the cluster-agent deployment has replicas > 1. (hot swap is meaningless at size=1).

**Comment by petersonfs** [comment]
I had a similar problem here. I just made the suggested workaround and it works.

**Comment by kaitlavs** [comment]
The issue has been fixed with this PR: https://github.com/DataDog/helm-charts/pull/521

**Comment by abe-winter** [comment]
thank you! that was so fast
