### ISSUE TITLE
Synthetics Private Location Logging Format Feedback

### ISSUE THREAD

**Issue by erikhjensen** [DataDog/helm-charts#544]
When ingesting the private location logs, in our case we host this in OpenShift, we see some less than ideal special characters in our implementation.  This is related to the header row.  This has a small complication as to the parsing.

**Describe what you expected:**
I expected the logs to be more easily parsed by the datadog platform. 

a) Firstly in what I believe to be a characterset conversion when the logs bubble up from the container to the console.out and are picked up by the containerized agent we see some character set issues.. see here:
2022-02-10 21:21:33 [[32minfo[39m]: 	[32mRequest processed[39m {
  "extraInfo": {
    "dnsNbAttempts": 1,

**square boxes and square brackets** I'm thinking this is similar to when I run a check from the console, how it has some colour coding.  I've seen similar translation to a characterset yielding these garbage chars.

b) so I would like to suggest datadog product team add a log processing pipeline in the ootb catalog which is able to grok this properly (assuming you're using a multi-line processor at the source ahead of time) Or, perhaps just log a more primitive log format to avoid this character conversion.

c) barring an ootb pipeline and primitive format, perhaps the whole log message could be json so that you get the attribute parse natively rather than this need to chain pipelines to grok the header and status and then leave the json payload to the ootb parser.

**Steps to reproduce the issue:**
Install the datadog private location in a containerized environment.
Review the logs in the log-streaming console in the k8s/openshift or, use the datadog logs agent to ship them to the platform and then review them in log-explorer.

**Additional environment details (Operating System, Cloud provider, etc):**
Azure Red Hat OpenShift
Linux

Example multi-line processor to clean up ingestion:

ad.datadoghq.com/synthetics-private-location.logs: >-
          [{"service":"synthetics-private-location-worker","source":"synthetics-private-location-worker","log_processing_rules":[{"type":"multi_line","name":"new_log_start_with_datestamp","pattern":"^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])\\s\\d{2}:\\d{2}:\\d{2}|\\[dumb-init\\]"}]}]

**Comment by erikhjensen** [comment]
Hi @clamoriniere  I wanted to share with your team the Grok parser that I developed.   I wasn't sure what to call the header-text so I nested it under "step" because it seems to be an internal compound-name which is also presented more cleanly as step.name.

as you can see, there's the odd whitespace characters \u001b and \[32m and whatnot, but I've mentioned those above in the OP.   

default %{_date} \[\u001b\[32m%{data:level}\u001b\[39m\]:\s\t\u001b\[32m%{data:step.headerLabel}\u001b\[39m %{data::json}

and the _date helper is:
_date %{date("yyyy-MM-dd HH:mm:ss"):timestamp}

Furthermore, pipeline-wise, because the [dumb-init] rows were being interpreted as error in the datadog platform I had the following pipeline structure:
1) Grok header and parse the native JSON component
2) Category Processor: Add level:info to [dumb-init]
3) Status Remapper: Define level as the official status of the log
4) Date Remapper: Define timestamp as the official timestamp of the log

after all this you get a pretty clean parse and attribute extraction.

**Comment by m-rousse** [comment]
Hi @erikhjensen,
You can set the log format to json using `--logFormat json` to start the private location. It is also possible to set it in the configuration file.
We started discussions to improve the default parsing of the private location logs too.
Thanks for the report.

**Comment by erikhjensen** [comment]
Hi Mathieu. I will this a try. And report back with specific findings.

**Comment by erikhjensen** [comment]
The logFormat property was a perfect response to my issue.

I've added logFormat to the json which we use as the kubernetes secret

it cleaned the logs right up and I removed the multi-line processing rule.
