### ISSUE TITLE
datadog chart version incompatibility in master

### ISSUE THREAD

**Issue by mars64** [DataDog/helm-charts#56]
**Describe what happened:**

The file [`datadog/helm-charts/charts/datadog/Chart.yaml` specifies `apiVersion: v1`](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/Chart.yaml#L1), which [Helm says means "use Helm v2"](https://helm.sh/docs/topics/charts/#the-apiversion-field) -- but this chart cannot `build` with `Helm v2`, I receive the error: 

```
charts/datadog $ helm2 version -c
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}

charts/datadog$ helm2 dependency build .               
Error: requirements.lock is out of sync with requirements.yaml
```

This works properly when built with v3: 

```
charts/datadog$ helm version -c     
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}

charts/datadog$ helm dependency build .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "banzaicloud-stable" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading kube-state-metrics from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

**Describe what you expected:**

I expect this chart to be correctly configured to utilize a Helm version that works. I _think_ that means I expect the `apiVersion` in the `Chart.yaml` to be `v2` to indicate that we ought to use `Helm v3` to build with. 

**Steps to reproduce the issue:**

Perform a `helm dependency build` on this chart using `Helm V2`.

**Additional environment details (Operating System, Cloud provider, etc):**

Under manual circumstances this isn't a big deal -- I can just use `v3` of the Helm binary, despite what the `Chart.yaml` says. But this completely breaks down when automating this process (for example, deploying the `datadog` chart with [ArgoCD](https://argoproj.github.io/argo-cd/)). Automation means that we must assume that the `Chart.yaml` is correct.

**Comment by vboulineau** [comment]
Hi @mars64,

So our chart is still compatible with Helm 2. So it's expected to keep `v1` and `requirements.yaml`.

However the last dependency update has been done with Helm 3, which has a different way of computing deps hashes, which breaks the Helm 2 compatibility when doing `helm dependency build`. Hopefully Helm 3 understand both hashes.

I've done a PR to fix this.

**Comment by mars64** [comment]
@vboulineau thanks for your consideration, I'm happy to use whatever functional Chart customers may be able to for now. 

But I must say, this seems like quite a backwards decision considering [the extended timeline for HelmV2 bugfixes has already expired, and security patches expire in less than 30 days](https://helm.sh/blog/helm-v2-deprecation-timeline/). Combined with the fact that [helm versions are built against k8s versions](https://helm.sh/docs/topics/version_skew/), it would appear that the toolchain Datadog depends on implies a maximum supported Kubernetes version of `1.16.x`.

**Comment by vboulineau** [comment]
Yes, however very much like Python2, Helm2 will not disappear once deprecated. Our goal is to have both Helm2/3 working correctly on this repository, which should be the case once this fix is merged.

Usually customers have a single toolchain that works with their Kubernetes clusters, and despite official versions skews, Helm 3 works well with Kubernetes 1.10 for instance.

**Comment by mars64** [comment]
Whatever your fix is will likely be just fine for my purposes, so I'll leave you to it. Clearly, I was impacted by Datadog's assumptions about how this stuff works, and referring to the upstream compatibility expectations doesn't seem to be getting me anywhere.

Thanks again for the help, I look forward to being able to use the product as intended.
