### ISSUE TITLE
Not sure of how to use apiKeyExistingSecret

### ISSUE THREAD

**Issue by red8888** [DataDog/helm-charts#60]
it looks like I can create a k8s secret myself and then set apiKeyExistingSecret to the name of that k8s secret for the api key right?

Do I have to create the k8s secret in a specific namespace for the datadog helm release to see it?

**Comment by clamoriniere** [comment]
Hi @red8888 

yes, you need to create a secret that contains the "API Key" and eventually the "APP key" in the namespace where you want to install the `datadog` helm chart.
the key in the secret must be: `api-key`

A simple command to creates this secret:
`kubectl create secret generic datadog-secret --from-literal api-key="<your apy key>" `

Please let me know if I answered your question.

**Comment by red8888** [comment]
oh duh that makes sense its just the same namespace I install the chart into? Can you confirm this series of commands is correct? 
```
# create secret in "dd-namespace"
kubectl create secret generic datadog-secret --from-literal api-key="<your apy key>" --namespace="dd-namespace"
# install chart to dd-namespace and specify the existing secret
helm upgrade --install "dd-namespace" --set datadog.apiKey=$(DATADOG_API_KEY) datadog/datadog)
```

Another question though, why do I need the APP for the chart install? APP key is for the application itself right? I should be injecting the APP key in my k8s deployments so my applications have access to it right?

**Comment by vboulineau** [comment]
Hello @red8888,

Your commands are correct. The application key is only used if you use the External Metrics feature of the Cluster Agent.

**Comment by amjanoni** [comment]
I had the same question, didn't find how to use the secret in the Helm apiKeyExistingSecret value until got into this issue, Thanks.

**Comment by rr-paras-patel** [comment]
How do we fetch secrets from AWS secret manager and configure helm chart to use it ? I see some documentation for a non-containerized agent. but i am looking for a solution to use with datadog helm chart.

**Comment by clamoriniere** [comment]
Hello, 
To use an external secret manager such as Vault or AWS secret manager. The agent can be extended thanks to the "secret backend" [feature](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux).

In summary: a process (binary, script) can be provided to the agent (with [some configuration](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux#kubernetes-secrets)). This process should implement the `secret backend` [interface](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux#the-executable-api), and call for the agent the external "secret manager".

In a containerised environment like kubernetes, you have 2 possibilities:
* the script can be accessible to agent thanks to a volume: configmap, hostpath. The helm chart allow you to add extra volume to the agent Daemonset. 
* You can build a customer agent image based on "gcr.io/datadoghq/agent" and copy the binary to the image.
  something like

  ```
  FROM gcr.io/datadoghq/agent:7.27.0
  COPY ./my-secret-backend.py /my-secret-backend.py
  ```

After in your to use it you can use `ENC["<mysecretidentifier>"]` in your agent configuration. So if it is for the API key, it can be the value that you store in the secret.

**Comment by bjd2385** [comment]
#369 may help explain this a bit better, but ultimately reading the docs on Secrets and, perhaps SealedSecrets, may help.
