### ISSUE TITLE
Expose of open_files_limit in helm

### ISSUE THREAD

**Issue by Unfaced85** [DataDog/helm-charts#600]
**Describe what happened:**
We use Datadog as part of our Openshift Cluster and recently stumbled upon the 
`Reached the limit on the maximum number of files in use:  100`
issue. Upon research I found out there is an option that can be used https://docs.datadoghq.com/logs/faq/how-to-increase-the-number-of-log-files-tailed-by-the-agent/

However, I do not seem to find this option exposed in the helm chart, whoch we are soley useing to configure our datadog agents

**Describe what you expected:**
a way to set the file limit  in datadog helm cahrt values.yaml

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
Openshift 4.9 Cluster with Datadog 2.30.5

**Comment by kaitlavs** [comment]
Hi @Unfaced85 

It would be difficult to add an option in the helm chart for each possible configuration parameter available for the agent. 

When an option is not available, the recommended solution is to add it as an environment variable. The relevant environment variable is documented here: https://docs.datadoghq.com/logs/faq/how-to-increase-the-number-of-log-files-tailed-by-the-agent/

`DD_LOGS_CONFIG_OPEN_FILES_LIMIT`

You would add this with the `datadog.env` parameter: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L315-L320

Your `values.yaml` would look like:

```
datadog:
  env:
  - name: DD_LOGS_CONFIG_OPEN_FILES_LIMIT
    value: <limit-number>
```

Let me know if this helps!

**Comment by Unfaced85** [comment]
Hi @kaitlavs thank you very much for your response - yes this helped us quite much and it worked for us.
Your Help is really appreciated, thanks.
