### ISSUE TITLE
Incorrect documentation on kube state core custom label collection

### ISSUE THREAD

**Issue by soumeng09** [DataDog/helm-charts#632]
**Describe what happened:**
https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L131
As per instructions here, if I want to add additional labels under datadog.kubeStateMetricsCore.labelsAsTags, I need to provide the exact label name as transformed by kube-state-metrics, including the "label_" prefix.

However the KMS Check code appends "label_" to the label name provided by user - https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/corechecks/cluster/ksm/kubernetes_state.go#L521

The instruction in the values file is misleading.

**Describe what you expected:**
My deployments have a label called kube_ci. If I want to add that label to kubernetes state tags, as per documentation I should do this in values file - 
`
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        label_kube_ci: kube_ci

`

However this does not work as KSM check adds another "label_" at the beginning and effectively tries to pull label named "label_label_kube_ci"

If I use just the label name (with all delimiters changed to _), that works - 
`
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        kube_ci: kube_ci
`
**Steps to reproduce the issue:**

1. Create deployment with "test" label

2. Add the test label as per documentation with the "label_" prefix in Datadog helm chart values file  - 
`
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        label_test: test

`
3. Go to Datadog Metrics Summary dashboard and search any metric of type kubernetes_state.deployment.* (e.g. - kubernetes_state.deployment.replicas_desired)

4. Expand the metrics, and under tags search with "test"

**Additional environment details (Operating System, Cloud provider, etc):**
Tested in AKS cluster (v1.21.7) with datadog helm chart version 2.33.5. However, this should be true for all kubernetes clusters.

**Comment by ahmed-mez** [comment]
Thank you for reporting it @soumeng09 !
