### ISSUE TITLE
Helm Error: UPGRADE FAILED: template: datadog/templates/cluster-agent-deployment.yaml:182:17

### ISSUE THREAD

**Issue by carbaugh-politico** [DataDog/helm-charts#649]
**Describe what happened:**
When trying to upgrade from datadog helm chart 2.28.13 to 2.34.4, I got the following error:

helm upgrade datadog datadog/datadog -f datadog-values.yaml --version 2.34.4 --dry-run

Error: UPGRADE FAILED: template: datadog/templates/cluster-agent-deployment.yaml:182:17: executing "datadog/templates/cluster-agent-deployment.yaml" at <eq .Values.clusterAgent.admissionController.configMode "service">: error calling eq: incompatible types for comparison

Section from datadog/templates/cluster-agent-deployment.yaml
          {{- if eq .Values.clusterAgent.admissionController.configMode "service" }}
          - name: DD_ADMISSION_CONTROLLER_INJECT_CONFIG_LOCAL_SERVICE_NAME
            value: {{ template "localService.name" . }}

Resolution:

Setting admissionController configMode specifically to hostip, the upgrade worked.

  admissionController:
    configMode: "hostip"

**Describe what you expected:**
From the values.yaml file, configMode doesn't seem to be set to the default hostip value if nothing is specified?

    # clusterAgent.admissionController.configMode -- The kind of configuration to be injected, it can be "hostip", "service", or "socket".
    ## If clusterAgent.admissionController.configMode is not set, the Admission Controller defaults to hostip.
    ## Note: "service" mode relies on the internal traffic service to target the agent running on the local node (requires Kubernetes v1.22+).
    ## ref: https://docs.datadoghq.com/agent/cluster_agent/admission_controller/#configure-apm-and-dogstatsd-communication-mode
    configMode:  # "hostip", "socket" or "service"

**Comment by davidor** [comment]
I got the same error when using an old version of Helm. Updating Helm to latest fixed the issue.
