### ISSUE TITLE
Daemonset template creates an empty dir /etc/redhat-release 

### ISSUE THREAD

**Issue by RWS9** [DataDog/helm-charts#677]
**Describe what happened:**
Daemonest template creates an empty dir `/etc/redhat-release` because the file doesn't exist, which results in “reboot” Ansible modules failing with an exception while trying to determine the distribution.

https://github.com/DataDog/helm-charts/blob/1949e235e08d20c92aeb09403533e0baaedc89e7/charts/datadog/templates/_daemonset-volumes-linux.yaml#L22

Ansible Side:
```
 "msg": "Failed to get distribution information. Missing \"ansible_distribution\" in output."
 ```
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/distribution.py#L182
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/distribution.py#L61

**Describe what you expected:**
Doemonset volume template won't create empty dir `/etc/redhat-release` in case the file is missing.

**Additional environment details (Operating System, Cloud provider, etc):**
Operating System
```
Ubuntu 20.04.4 LTS (Focal Fossa)
```

Kubernetes
```
v1.22.11 linux/amd64
```

**Comment by maxpain** [comment]
The same problem.

**Comment by clamoriniere** [comment]
Hi @RWS9 and @maxpain 

From datadog chart `2.37.8` , the option `datadog.systemProbe.enableDefaultOsReleasePaths` set to `false` allow you to avoid the agent daemonset to mount the missing folder from on the host. 

the proper path can still be provided thanks to `datadog.osReleasePath`  information. default value is `/etc/os-release`

**Comment by fculpo** [comment]
Same issue here, I think DD agent should not create unrelated OS directories on our hosts.
Ansible had an exception getting os_family, on which most of out playbooks depend.

Besides, by default k8s/Linux will create a folder, while redhat-release is supposed to be a file.

enableDefaultOsReleasePaths shoud probably be false by default
