### ISSUE TITLE
Installation Failed - Invalid Semantic Version

### ISSUE THREAD

**Issue by jblamber** [DataDog/helm-charts#689]
**Describe what happened:**

Following the basic agent installation instructions on a new EKS cluster ( k8s 1.21 ) and I see an INSTALLATION FAILED error, where previously it would work flawlessly on the same cluster/client/helm versions. Did version requirements change somewhere I didn't see?

**Describe what you expected:**

Up until a few days ago, a successful installation of agent and cluster agent. But tried yesterday on a new cluster (same k8s version) and see the below issue.

**Steps to reproduce the issue:**

```
<Provision new eks cluster 1.21>
<update kubeconfig>
<verify kubeconfig correct by listing pods>
helm repo add datadog https://helm.datadoghq.com
helm install my-datadog-operator datadog/datadog-operator
```

Results in

```
Error: INSTALLATION FAILED: template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
```

**Additional environment details (Operating System, Cloud provider, etc):**

helm version 3.9.1 (tried previously on a 3.8.2 version and upgraded to try to resolve)
aws cli version 2.7.15
k8s server 1.21
kubectl client 1.23

**Comment by jblamber** [comment]
I believe this is due to this change:

https://github.com/DataDog/helm-charts/commit/5d87c07c95457e4a8b6eb73c57d7339c260eb180

**Comment by CharlyF** [comment]
Hi @jblamber - sorry for the headache. I'm looking into it now.

**Comment by CharlyF** [comment]
👋 @jblamber, just wanted to circle back to make sure this solved your issue.

**Comment by jblamber** [comment]
Still failing. Went from a `<21` error to `<=21` error. I tried a helm repo update after 690 and still got

```
Error: INSTALLATION FAILED: template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
```

then again this morning after 691 and now get

```
Error: INSTALLATION FAILED: template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<=21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
```

Forgive my helm inexperience, but which version of what component is it complaining about?

```
kubectl version
>>>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-eks-84b4fe6", GitCommit:"e1318dce57b3e319a2e3fecf343677d1c4d4aa75", GitTreeState:"clean", BuildDate:"2022-06-09T18:22:07Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jblamber** [comment]
`kubectl config view`
```
name: arn:aws:eks:us-west-2:<accountid>:cluster/prod-<name>-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - prod-<name>-eks
```

**Comment by jblamber** [comment]
@CharlyF I think the issue is still open.

**Comment by jblamber** [comment]
@CharlyF  should I open a new issue? Still unable to deploy I think due to the 21+ semver.

**Comment by EqbalS** [comment]
I have the same problem

**Comment by rajivchirania** [comment]
So i am also facing the same issue while upgrading dadadog operator from 0.8.0 to 0.8.4

I am still unable to understand what was the fix..
