### ISSUE TITLE
DataDog Agent datadog-2.36.4 Helm Chart deploys Ubuntu 21.10

### ISSUE THREAD

**Issue by PartTimeLegend** [DataDog/helm-charts#695]
**Describe what happened:**

# cat /etc/lsb-release
Pod: kube-system/datadog-agent-6qqwc | Container: agent
root@datadog-agent-6qqwc:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"

**Describe what you expected:**

As per the [Dockerfile](https://github.com/DataDog/datadog-agent/blob/main/Dockerfiles/agent/amd64/Dockerfile) I would have expected this to deploy the 22.04 LTS as the container base.

**Steps to reproduce the issue:**

Use helm to install datadog-2.36.4 into your cluster.
Connect shell to a datadog agent pod and then run cat /etc/lsb-release

**Additional environment details (Operating System, Cloud provider, etc):**

AWS EKS

**Comment by davidor** [comment]
This is expected. The latest version of the deploys agent v7.37.1 (the latest release) which uses ubuntu 21.10:
https://github.com/DataDog/datadog-agent/blob/7.37.1/Dockerfiles/agent/amd64/Dockerfile

https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L1008

**Comment by PartTimeLegend** [comment]
Thank you. I knew it must have been something obvious.
