### ISSUE TITLE
cluster-checks runner cannot run snmp/network device checks due to removed profiles

### ISSUE THREAD

**Issue by nickvecelliooo** [DataDog/helm-charts#711]
**Describe what happened:**
The cluster-check runner cannot run SNMP checks due to the following error:
```
Error: could not load snmp:
* Core Check Loader: Could not configure check snmp: build config failed: failed to load default profiles: failed to get default profile definitions: failed to read dir `/etc/datadog-agent/conf.d/snmp.d/profiles`: open /etc/datadog-agent/conf.d/snmp.d/profiles: no such file or directory
```

The is is due to the cluster-check command args running `rm -rf /etc/datadog-agent/conf.d` https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L103 which deletes the snmp.d/profiles directory needed for the snmp check to run

**Describe what you expected:**
The cluster-check runner should be able to run SNMP checks, as implied in the cluster-check runner docs
```
...the Cluster Checks Runner is specifically dedicated to running [cluster checks](https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/), which monitor internal Kubernetes services, as well as external services like managed databases and network devices.
```

**Steps to reproduce the issue:**
Set the value for `clusterChecksRunner.enabled` to `true`. Supply an snmp config file to `clusterAgent.confd` with `cluster_check` set to `true`. Jump into the cluster-check-runner pod and run `agent check snmp`; error will be produced.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by CharlyF** [comment]
Hi @nickvecelliooo - Thanks for opening this issue, and sorry about the headache. I am adding it to our backlog.

**Comment by mitchellmaler** [comment]
I was able to get snmp checks to work using snmp_listener and autodiscovery outlined here:
https://docs.datadoghq.com/network_monitoring/devices/guide/cluster-agent/

**Comment by nickvecelliooo** [comment]
@mitchellmaler that's not the problem - the problem is that the cluster check runners remove the check directories that contain the snmp profiles due to the rm command that is run on startup as stated in the original issue report; what you've suggested applies the check out as cluster checks to the individual agents in the cluster - not the dedicated cluster check runners.

**Comment by mitchellmaler** [comment]
After configuring the snmp checks outlined in that document using the listener config it is running them from the cluster agent check runners and not from a node agent.

**Comment by mitchellmaler** [comment]
The cluster agent delegates the check out to the check runners when those are enabled. I guess if that is not the cluster agent itself would run them I believe.

**Comment by nickvecelliooo** [comment]
That method _does_ work, except theres a few significant issues that make it moot
1. that only works for the python check, not the Go based snmp check by setting `loader: core` in init_config
2. makes providing custom profiles significantly more difficult, since the profiles used are deep in embedded agent directory, rather than the convenient `/etc/datadog-agent/conf.d/snmp.d/profiles`
3. this only works for discovery, not static configuration through `ip_address` based configs

Change your snmp.yaml config to
```
init_config:
  loader: core
```
and re-apply the chart. Within the cluster agent logs you'll see something like
```
2022-10-06 14:52:04 UTC | CLUSTER | INFO | (pkg/clusteragent/clusterchecks/dispatcher_main.go:139 in add) | Dispatching configuration snmp:d4029d819be50dbc to node datadog-clusterchecks-84f44cdcf9-tvg9b
```
but then running the check on the cluster check runner will give you 
```
2022-10-06 14:52:10 UTC | CORE | ERROR | (pkg/collector/corechecks/loader.go:72 in Load) | core.loader: could not configure check snmp: build config failed: failed to load default profiles: failed to get default profile definitions: failed to read dir `/etc/datadog-agent/conf.d/snmp.d/profiles`: open /etc/datadog-agent/conf.d/snmp.d/profiles: no such file or directory
```
which is a direct result of the originally reported problem; the conf.d directory containing the profiles is removed here https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L103 and there is no way to override that behavior

So while the snmp_listener stuff you mentioned does work, it significantly hamstrings the ability of the snmp check and requires it to run the python version of the check in autodiscovery mode with provided profiles (effectively) only. Having implemented this SNMP check across hundreds of networks, it's often desired to run a configuration based on static IPs, and the python check just cant handle hundreds of those at once, and there is a significant need for custom profiles - the snmp_listener based workaround is just not sufficient.

**Comment by celenechang** [comment]
Hi @nickvecelliooo , thank you for opening this issue and apologies for the delay in addressing it. I believe it has been fixed with https://github.com/DataDog/helm-charts/pull/1594 . I will close this issue but please let us know if you have additional feedback.
