### ISSUE TITLE
Image digest not supported - Datadog helm chart

### ISSUE THREAD

**Issue by francRang** [DataDog/helm-charts#714]
**Describe what happened:**
Image Digest not supported.

**Describe what you expected:**
Need a way to use an image digest for a given image.
If I pass an image digest as a tag, it will render in a way that does not work as intended.
For example:
`"{{.Values.agents.image.repository}}:{{.Values.agents.image.tag}}"`
Would render something like this:
`myimagerepository:sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108`

This will not work as expected, the result I want is something as follows:
`myimagerepository@sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108`

**Steps to reproduce the issue:**

Pass an image digest as a value under **value.yaml** for any of the image.tag fields supported and do a `helm template`.

**Comment by CharlyF** [comment]
hello @francRang - Thanks for opening this up. 
Indeed this is something not supported. Out of curiosity, is it not possible for you to use the image name and tag?

**Comment by francRang** [comment]
Hi @CharlyF! unforunately it is not because it will be adding an extra ":" and it will not add the necessary "@" as the example above:
Want: `myimagerepository@sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108`
Getting:  `myimagerepository:sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108`

Working on an MR to expand the `static/templates/_helpers.tpl` to support this feature.
