### ISSUE TITLE
IaaC - resources re-created on every deploy

### ISSUE THREAD

**Issue by dstoyanoff** [DataDog/helm-charts#718]
**Describe what happened:**
I am using Pulumi, but it would be valid for terraform as well I suppose.

I have a datadog helm chart in my project. The issues is that on every deployment, 3 of the resources are always re-created
- Secret - datadog-cluster-agent
- Deployment - datadog-cluster-agent
- DaemonSet - datadog

I can see that the change is in annotations/checksum/clusteragent_token and also the whole secret is replaced. Is that the intended behavior with no way to override it? For me this update takes costs 2 minutes on every deployment, which I'd like to avoid.

**Describe what you expected:**
All resources should not be re-created every time as this increases build time by few minutes.

**Additional environment details (Operating System, Cloud provider, etc):**
Deploying on GKE.

**Comment by vboulineau** [comment]
Hello @dstoyanoff,

That's indeed because, by default the Cluster Agent is autogenerated (random), thus always replaced.
You can solve that by using a fixed secret by setting the `clusterAgent.tokenExistingSecret` value.

**Comment by dstoyanoff** [comment]
That's a life saver! Thanks a lot!
