### ISSUE TITLE
Helm upgrade broken - windows nodes - Not found: "os-release-file"

### ISSUE THREAD

**Issue by danbrad** [DataDog/helm-charts#729]
**Describe what happened:**

On upgrading DD on an AKS cluster with *windows* node pools, we see this error:

```
UPGRADE FAILED: cannot patch "datadog-windows" with kind DaemonSet: DaemonSet.apps "datadog-windows" is invalid: [spec.template.spec.containers[0].volumeMounts[3].name: Not found: "os-release-file", spec.template.spec.containers[2].volumeMounts[3].name: Not found: "os-release-file"]
```

I suspect this was broken in https://github.com/DataDog/helm-charts/pull/717

**Describe what you expected:**

The upgrade to proceed correctly

**Steps to reproduce the issue:**

Upgrde DataDog on a k8s cluster with windows nodes.

**Additional environment details (Operating System, Cloud provider, etc):**

Windows, Azure

**Comment by clamoriniere** [comment]
Hi @danbrad 

Sorry about this issue, we are working on a fix. it should land soon.

**Comment by dstoyanoff** [comment]
Same issue here. Thanks @clamoriniere for the update. Is there a workaround to this? Downgrade to another version or something else?

**Comment by danbrad** [comment]
Downgrading to 2.37.4 worked for me

**Comment by rslinckx** [comment]
@clamoriniere Don't know if it's related but I left a comment on the PR as well regarding duplicate volume mount here: https://github.com/DataDog/helm-charts/pull/717#issuecomment-1228231227

**Comment by clamoriniere** [comment]
Hi @danbrad

could you share the `values.yaml` file that you use for the `datadog-windows`  helm release 🙇 

@rslinckx we will look at this issue too.
