### ISSUE TITLE
Helm stable chart repository will be removed in the future

### ISSUE THREAD

**Issue by int128** [DataDog/helm-charts#75]
Hi,

**Describe what happened:**
Datadog chart depends on `stable/kube-state-metrics` chart. According to [the deprecation announce](https://github.com/helm/charts#deprecation-timeline), stable chart will be removed on Nov 13, 2020. I think it will cause a deployment failure.

Please let me know some workaround, for example, deploying kube-state-metrics from [here](https://github.com/kubernetes/kube-state-metrics) or alternative chart.

**Additional environment details (Operating System, Cloud provider, etc):**
We are using Datadog chart with the following value:

```yaml
datadog:
  kubeStateMetricsEnabled: true
```

**Comment by clamoriniere** [comment]
@int128 
Thank you for opening this issue, we will update `kube-state-metrics` dependency before the removal

**Comment by clamoriniere** [comment]
lets wait to have this PR merged https://github.com/kubernetes/kube-state-metrics/issues/1153
