### ISSUE TITLE
DataDog chart version 2.4.34 is broken: illegal number syntax: "-"

### ISSUE THREAD

**Issue by hilsenrat** [DataDog/helm-charts#84]
**Describe what happened:**
When trying to install DataDog chart (version 2.4.34), the installation fails with the following error:
```
Error: UPGRADE FAILED: parse error in "datadog/templates/_helpers.tpl": template: datadog/templates/_helpers.tpl:194: illegal number syntax: "-"
```

Installation of the previous version (2.4.33) on the exact same infrastructure finished as expected.
It looks related to this [PR](https://github.com/DataDog/helm-charts/commit/b65e153b5d0adf4174230ad47078915f47a88b66).

**Describe what you expected:**

Successful installation of DataDog.

**Steps to reproduce the issue:**
`helm upgrade --install datadog/datadog --version 2.4.34 datadog`

**Additional environment details (Operating System, Cloud provider, etc):**
kubernetes: 1.16
helm: 2.14

**Comment by clamoriniere** [comment]
Hi @hilsenrat 
Thanks you for reporting this issue,

Could you share your `values.yaml` file?  I'm currently testing it with helm v2.16.7 and it seems to work

**Comment by hilsenrat** [comment]
Hi @clamoriniere,
Thanks for your response. I see that you committed a fix, do you still need me to export the values file?

**Comment by clamoriniere** [comment]
No thank you :)
I think i have founded the issue: it was an extra space in the `{{- if -}}` condition that triggers a bug in the golang lexer.

**Comment by hilsenrat** [comment]
Great, thanks for the quick response and resolution.
I'll deploy the new version once it'll be merged and then will close the issue.

**Comment by hilsenrat** [comment]
2.4.36 worked in my environment.
Thanks @clamoriniere.
