### ISSUE TITLE
Chart for operator 0.8.3 uses image for 0.8.1 by default

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/helm-charts#866]
**Describe what happened:**
Deploying the operator via helm chart 0.9.1, which is labeled as `appVersion: 0.8.3` instead [uses the image](https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/values.yaml#L45) for operator 0.8.1.

**Describe what you expected:**
The operator should be deployed at version 0.8.3, in keeping with the chart's `appVersion`.

**Steps to reproduce the issue:**
Install with a minimal, default configuration using the datadog-operator helm chart.  Observe that the container image for the operator is deployed at 0.8.1.

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon EKS 1.22

**Comment by CharlyF** [comment]
Hello @jcogilvie - Thanks for reaching out.
Could you try to upgrade the operator to 0.9.2, this should show the new image, `0.8.4`.
Per https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/Chart.yaml#L3-L4

Best,

**Comment by levan-m** [comment]
Resolving since we haven't received any update. Feel free to reopen if the problem arises.
