### ISSUE TITLE
Datadog agent sytem probe fail on GKE 1.22+ failed mkdir /usr/src

### ISSUE THREAD

**Issue by ovrdoz** [DataDog/helm-charts#867]
**Describe what happened:**
After installing the agent on GKE 1.22+ , the system probe showed constant failures, preventing the agent from being active.
this message error:
`mkdir /usr/src: read-only file system`

**Describe what you expected:**
the agent was expected to go up normally but unfortunately it was not active

**Steps to reproduce the issue:**
run chart install command as below the error 
```
# helm v3
helm -n monitoring upgrade datadog-agent datadog/datadog  \  
  --set "clusterName=my-production" \     
  --set "podLabelsAsTags.tags={env:my-production}" \
  --debug
```
**Additional environment details (Operating System, Cloud provider, etc):**
GKE 1.22+
```
# cat  /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=8339df9b3f28bad265f645cad9d96530c90d8675
GOOGLE_CRASH_ID=Lakitu
VERSION=93
VERSION_ID=93
```

**Comment by ovrdoz** [comment]
my gke 1.22+ installation does not have the source directory /usr/src …. the datadog agent tries and tries to mount and therefore crashes, my suggestion is to apply the block in the system probe as optional.

```
{{- if and (eq (include "runtime-compilation-enabled" .) "true") .Values.datadog.systemProbe.enableDefaultKernelHeadersPaths }}
    - name: modules
      mountPath: /lib/modules
      mountPropagation: {{ .Values.datadog.hostVolumeMountPropagation }}
      readOnly: true
{{- if .Values.datadog.systemProbe.enableDefaultUserSourcePaths }} }} # <<< this
    - name: src
      mountPath: /usr/src
      mountPropagation: {{ .Values.datadog.hostVolumeMountPropagation }}
      readOnly: true
{{- end }}
{{- end }}
```

**Comment by clamoriniere** [comment]
Hi @ovrdoz 

For reporting this issue.

@ISauve @CharlyF, I think you worked recently on some PR related to this option. Could you review @ovrdoz idea to solve the issue?

**Comment by johanneswuerbach** [comment]
Looks like this is related https://github.com/DataDog/helm-charts/pull/838, setting `datadog.systemProbe.enableDefaultKernelHeadersPaths=false` is resolving the issue for us.

**Comment by ovrdoz** [comment]
Hi @johanneswuerbach, this solution only resolves part of the problem because it excludes the "/lib/modules" path. This path is important for the Datadog agent to read because it contains important kernel headers and modules that are necessary for the agent to properly monitor the system and provide accurate data. Without access to this information, the agent may not be able to fully assess the health and performance of the system.

**Comment by kubaracek** [comment]
Anyone running into this. If you're on GKE, set this `providers.gke.cos=true`
