### ISSUE TITLE
Missing Secret annotations in the datatdog helm chart

### ISSUE THREAD

**Issue by maximumG** [DataDog/helm-charts#882]
**Describe what happened:**

The datadog helm chart lacks support for annotations on Secrets. We are extensively using Secret to mutate values using annotations as mutating materials.

**Describe what you expected:**

A new helm value such as `agents.SecretAnnotations`. This values would be referenced inside the Secrets helm templates. This pattern has already been setup for pods `agents.PodAnnotations`

**Steps to reproduce the issue:**

N/A

**Additional environment details (Operating System, Cloud provider, etc):**

N/A

**Comment by clamoriniere** [comment]
Hi @maximumG,

can it be ok, if we define a list of annotations `globalAnnotations` that will be applied to any resources created by the chart?

**Comment by Izzette** [comment]
> Hi @maximumG,
> 
> can it be ok, if we define a list of annotations `globalAnnotations` that will be applied to any resources created by the chart?

It would work for our specific use-case, yes 🙂

**Comment by maximumG** [comment]
> can it be ok, if we define a list of annotations globalAnnotations that will be applied to any resources created by the chart?

As @Izzette mentioned it will definitely handle our use case. Do you want me to update my PR with such new feature ?

**Comment by clamoriniere** [comment]
@maximumG 
I think we can keep the change you made in the PR#883. I will review it
