### ISSUE TITLE
GKE Autopilot failing to deploy for Rapid Release Channel

### ISSUE THREAD

**Issue by JacksonDavenport** [DataDog/helm-charts#894]
(Creating as follow up to #549 This is already being tracked internally as well)

**Describe what happened:**
Failure to deploy Helm chart in GKE Autopilot when using _Rapid Release Channel_. Seen in versions:

- 1.26.0-gke.2000
- 1.25.5-gke.2000
- 1.25.5-gke.1500 (default)

With error:
```
Error: UPGRADE FAILED: cannot patch "datadog" with kind DaemonSet: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {
  "[denied by autogke-no-write-mode-hostpath]": [
    "hostPath volume runtimesocketdir used in container agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume procdir used in container agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume cgroups used in container agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume runtimesocketdir used in container process-agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume cgroups used in container process-agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume passwd used in container process-agent uses path /etc/passwd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume procdir used in container process-agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].",
    "hostPath volume runtimesocketdir used in container init-config uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."
  ]
}
Requested by user: '<USER>', groups: 'system:authenticated'.
```

This starts occurring with Helm Chart version `3.6.9`. 

As a **workaround** can pin to version `3.6.8`.
```shell
helm upgrade datadog -f values.yaml datadog/datadog --version 3.6.8
```

**Describe what you expected:**
For these non-host path volumes to be okay in GKE Autopilot / Agent DaemonSet to deploy correctly.

**Steps to reproduce the issue:**
Can use barebones config and deploy in 3.6.8 (good), 3.6.9+ (bad) to get that above error in the Rapid Release Channel versions.
```yaml
datadog:
  apiKey: <KEY>

providers:
  gke:
    autopilot: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

GKE Autopilot is restricting the addition of the new volume mount added in 3.6.9 for the auth token #868. Interestingly this volume / volumeMount are from an `emptyDir: {}` type of volume, which we use in several places already. The issue isn't necessarily with _this volume_ added in 3.6.9, but _any_ new volumeMount added. 

For example the following should be okay, but likewise caused it to get restricted in the good 3.6.8 version.

```yaml
agents:
  volumeMounts:
    - name: test
      mountPath: /var/log/test

  volumes:
    - name: test
      emptyDir: {}

providers:
  gke:
    autopilot: true
```

**Comment by JacksonDavenport** [comment]
Fixed in Helm Chart version `3.10.5`

- https://github.com/DataDog/helm-charts/pull/901

**Comment by brettcurtis** [comment]
I'm working on a ticket (1086523) and when trying to get the flare on the DeamonSet PODs I get this error:

```none
kubectl exec -it datadog-8nrpz agent status
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "agent" out of: agent, process-agent, init-volume (init), init-config (init)
Error from server (GKE Warden constraints violations): admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-no-pod-connect-limitation]":["Cannot connect to pod datadog/datadog-8nrpz, with annotation \"autopilot.gke.io/no-connect\": \"true\"."]}
Requested by user: 'myuser@mydomain.com', groups: 'system: authenticated'.
```

This related to this issue or #549 ?

**Comment by JacksonDavenport** [comment]
> I'm working on a ticket (1086523) and when trying to get the flare on the DeamonSet PODs I get this error:
> 
> ```
> kubectl exec -it datadog-8nrpz agent status
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
> Defaulted container "agent" out of: agent, process-agent, init-volume (init), init-config (init)
> Error from server (GKE Warden constraints violations): admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
> Violations details: {"[denied by autogke-no-pod-connect-limitation]":["Cannot connect to pod datadog/datadog-8nrpz, with annotation \"autopilot.gke.io/no-connect\": \"true\"."]}
> Requested by user: 'myuser@mydomain.com', groups: 'system: authenticated'.
> ```
> 
> This related to this issue or #549 ? I can get a flare on my cluster-agent with no problems.

Hey Brett, that is a bit of a different issue here, and in this case expected. The error
```json
Violations details: 
{
  "[denied by autogke-no-pod-connect-limitation]":["Cannot connect to pod datadog/datadog-8nrpz, with annotation \"autopilot.gke.io/no-connect\": \"true\"."]
}
```

The Datadog Agent is a part of the trusted workloads for GKE Autopilot. 
- https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-partners

So while our DaemonSet / agent pod do get greater capabilities otherwise restricted in Autopilot - the DaemonSet has some stricter constraints on what it looks like. This includes a few of the things in 549 for its formatting. This also includes the rules that "Remove functionality such as kubectl exec for workloads with elevated privileges."

When creating these pods GKE will automatically add that annotation `"autopilot.gke.io/no-connect\": \"true\"` to these pods, signifying you can't connect / exec commands with them. This is a bit of a newer change so older clusters might still have that capability. 

I just chatted with the support engineer assigned on your ticket regarding some alternatives to gathering this information through a flare. In general though if you'd like to see information on the Agent information:
- `kubectl logs <Agent Pod> -c agent > agent.log` is still supported to grab logs
- The Infrastructure List should show the running Agent Integrations per host, this can often show the integration issue that you would see logged in the status output. That being said if the Agent Integration isn't running in the first place, such as due to invalid Autodiscovery Annotations, you wouldn't see it listed

**Comment by brettcurtis** [comment]
@JacksonDavenport Thanks for the detailed response, that clears things up for sure. This will give us something to dig into in the morning! Thanks again 💪
