### ISSUE TITLE
[helm-charts/charts/datadog] Cluster agent: support for custom podAntiAffinity

### ISSUE THREAD

**Issue by drmaciej** [DataDog/helm-charts#899]
**Describe what happened:**
We are using managed node groups in our EKS clusters, and we have a managed node group per availability zone. It has happened during an AMI rollout that both pods of the cluster agent were down at the same time. Same thing happened to a few of our internal components, so to solve for it we added a podAntiAffinity to spread Deployments across availability zones using `topologyKey: "topology.kubernetes.io/zone"`. Importantly, we did it using `requiredDuringSchedulingIgnoredDuringExecution` rather than `preferredDuringSchedulingIgnoredDuringExecution`.

**Describe what you expected:**
The ability to specify `podAntiAffinity` rather than relying on a default one: https://github.com/DataDog/helm-charts/blob/datadog-3.10.4/charts/datadog/templates/cluster-agent-deployment.yaml#L346-L353.

**Comment by clamoriniere** [comment]
Hi @drmaciej 

I think it is already possible to do with the option:  `clusterAgent.affinity`
However with this option you will need to redefine completely the podTemplateSpec "affinity" part defined in a deployment at  `.spec.template.affinity`
