### ISSUE TITLE
Cluster Agent SCC

### ISSUE THREAD

**Issue by jlamande** [DataDog/helm-charts#907]
**Describe what happened:**

The template `charts/datadog/templates/cluster-agent-scc.yaml` contains twice the `users` attribute. This is incorrect as `Map keys must be unique`

**Describe what you expected:**
No yaml issue

**Steps to reproduce the issue:**
open `charts/datadog/templates/cluster-agent-scc.yaml` in a yaml-powered editor

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hi @jlamande 

For for reporting this issue, I was able to confirm the issue. It will be fix it soon.
