### ISSUE TITLE
appKeyExistingSecret support is broken in datadog chart using daemonset

### ISSUE THREAD

**Issue by gothrek22** [DataDog/helm-charts#908]
**Describe what happened:**

Deploying the datadog chart with the newest version causes it to not start as datadog daemonset requires appKey, but `appKeyExistingSecret` is not configured in the template.

**Describe what you expected:**

`appKeyExistingSecret` should be used in the template just like `apiKeyExistingSecret` is.

**Steps to reproduce the issue:**

Doesn't really matter. As you can see it missing in the template.

Use daemonset in datadog chart using `appKeyExistingSecret` instead of the value directly.

**Additional environment details (Operating System, Cloud provider, etc):**

Doesn't really matter.

**Comment by clamoriniere** [comment]
Hi @gothrek22 

The App-key is only used by the "cluster-agent" deployment, not the "agent" daemonset. 
So it is ok that the app "appKeyExistingSecret" is not use in the `daemonset.yaml` template.

Also the `app-key` is only use for few feature in the "cluster-agent", this is why we are still able to create the "cluster-agent" deployment even if the `app-key` (with a secret or in the ) is not provided

Could you share your `values.yaml` or the command use to deploy the chart, so we can better understand the usecase and the issue. 
thanks 🙇

**Comment by gothrek22** [comment]
Seems I was an idiot 🤦 It's working fine.

**Comment by clamoriniere** [comment]
@gothrek22 

No problem. I was happy to help, and that the agent deployment finally works fine for you.
