### ISSUE TITLE
Enable datadog.kubelet.tlsVerify again on AKS

### ISSUE THREAD

**Issue by PSanetra** [DataDog/helm-charts#972]
The original reason to disable tlsVerify ok AKS is fixed since January: https://github.com/Azure/AKS/issues/2770

Therefore enabling tlsVerify again in the AKS examples would be nice:
[agent_on_aks_values.yaml#L19](https://github.com/DataDog/helm-charts/blob/d997c19f90dc13f20e29b5ffcd202621e16915c8/examples/datadog/agent_on_aks_values.yaml#L19)

**Comment by levan-m** [comment]
Hello, thank for bringing this up and sorry it took us a while to address it. Example file was updated with this PR https://github.com/DataDog/helm-charts/pull/1176.
