### ISSUE TITLE
customAgentConfig isn't supported on windows nodes

### ISSUE THREAD

**Issue by blvckmaze** [DataDog/helm-charts#977]
**Describe what happened:**

  `agents.customAgentConfig`  behaves like a bind-mounted file on Windows nodes, which is not supported, because in case of bind-mounts windows can handle only directories. 
Here's an example of an error:

```
Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\c04c070d-6345-4f49-b6a9-dea475b857de\volumes\kubernetes.io~configmap\datadog-yaml\datadog.yaml:C:/ProgramData/Datadog/datadog.yaml:ro': invalid mount config for type "bind": source path must be a directory
```

**Describe what you expected:**

It would be great to have a different approach for Windows nodes, although I'm not sure what that would be. Perhaps something similar to `datadog.confd` or feeding config path to agent executable.

**Steps to reproduce the issue:**

- Set `agents.useConfigMap` to `true`
- Add any configuration to `agents.customAgentConfig`
- Deploy the Datadog chart to a Windows-based EKS node

**Additional environment details (Operating System, Cloud provider, etc):**

- OS: Any windows version
- Cloud provider: AWS
- Cloud service: EKS

**Comment by CharlyF** [comment]
Hey @blvckmaze - I just wanted to ack this. 
Apologies for the headache, we are going to look into it.
